### ISSUE TITLE
invalid metric name with null byte crashes persistence of all metrics

### ISSUE THREAD

**Issue by jackhammer2k** [graphite-project/carbon#356]
Due to an error in our application we have sent a metric name with a null byte via TCP to Carbon cache. This results in following error message in log:

```
07/01/2015 10:03:14 :: Unhandled Error
Traceback (most recent call last):
  File "/usr/lib64/python2.6/threading.py", line 484, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib64/python2.6/site-packages/twisted/python/threadpool.py", line 172, in _worker
    result = context.call(ctx, function, *args, **kwargs)
  File "/usr/lib64/python2.6/site-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib64/python2.6/site-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/usr/lib/python2.6/site-packages/carbon/writer.py", line 158, in writeForever
    writeCachedDataPoints()
  File "/usr/lib/python2.6/site-packages/carbon/writer.py", line 91, in writeCachedDataPoints
    for (metric, datapoints, dbFilePath, dbFileExists) in optimalWriteOrder():
  File "/usr/lib/python2.6/site-packages/carbon/writer.py", line 54, in optimalWriteOrder
    dbFileExists = exists(dbFilePath)
  File "/usr/lib64/python2.6/genericpath.py", line 18, in exists
    st = os.stat(path)
exceptions.TypeError: stat() argument 1 must be encoded string without NULL bytes, not str
```

Because we could still access our statistics we didn't noticed that Carbon is not persisting incoming metrics anymore. Queue caches did increase continuously until it crashed with out of memory. We've lost all metrics within this period, because this one invalid metric did abort persistence of all further metrics.

Robustness of Carbon needs to be improved here.

**Comment by obfuscurity** [comment]
We probably just need to catch that TypeError exception on the `exists(dbFilePath)`.
