### ISSUE TITLE
Confusing pickle/UnboundLocalError with distributed graphite cluster

### ISSUE THREAD

**Issue by theJohnnyBrown** [graphite-project/carbon#421]
I have a graphite cluster running on three ec2 nodes. Each node has five carbon-cache processes and a relay. I've notice periods where suddenly one metric or another will stop being recorded. (i.e. the line on my grafana stops), and I've noticed that these periods of missing data seem to coincide with messages in the logs that look like this: 

```
2015-08-05_22:58:28.46517 05/08/2015 16:58:28 :: [listener] MetricPickleReceiver connection with 127.0.0.1:58303 lost: local variable 'value' referenced before assignment
2015-08-05_22:58:28.46693 05/08/2015 16:58:28 :: [listener] MetricPickleReceiver connection with 127.0.0.1:58306 established
2015-08-05_22:58:28.46708 05/08/2015 16:58:28 :: [listener] Error decoding pickle: too many values to unpack
2015-08-05_22:58:28.46729 05/08/2015 16:58:28 :: [console] Unhandled Error
2015-08-05_22:58:28.46731 Traceback (most recent call last):
2015-08-05_22:58:28.46731   File "/usr/lib64/python2.6/site-packages/twisted/python/log.py", line 88, in callWithLogger
2015-08-05_22:58:28.46731     return callWithContext({"system": lp}, func, *args, **kw)
2015-08-05_22:58:28.46731   File "/usr/lib64/python2.6/site-packages/twisted/python/log.py", line 73, in callWithContext
2015-08-05_22:58:28.46732     return context.call({ILogContext: newCtx}, func, *args, **kw)
2015-08-05_22:58:28.46732   File "/usr/lib64/python2.6/site-packages/twisted/python/context.py", line 118, in callWithContext
2015-08-05_22:58:28.46732     return self.currentContext().callWithContext(ctx, func, *args, **kw)
2015-08-05_22:58:28.46732   File "/usr/lib64/python2.6/site-packages/twisted/python/context.py", line 81, in callWithContext
2015-08-05_22:58:28.46732     return func(*args,**kw)
2015-08-05_22:58:28.46732 --- <exception caught here> ---
2015-08-05_22:58:28.46733   File "/usr/lib64/python2.6/site-packages/twisted/internet/posixbase.py", line 601, in _doReadOrWrite
2015-08-05_22:58:28.46733     why = selectable.doRead()
2015-08-05_22:58:28.46733   File "/usr/lib64/python2.6/site-packages/twisted/internet/tcp.py", line 215, in doRead
2015-08-05_22:58:28.46733     return self._dataReceived(data)
2015-08-05_22:58:28.46733   File "/usr/lib64/python2.6/site-packages/twisted/internet/tcp.py", line 221, in _dataReceived
2015-08-05_22:58:28.46734     rval = self.protocol.dataReceived(data)
2015-08-05_22:58:28.46734   File "/usr/lib64/python2.6/site-packages/twisted/protocols/basic.py", line 765, in dataReceived
2015-08-05_22:58:28.46734     self.stringReceived(packet)
2015-08-05_22:58:28.46734   File "/opt/graphite/lib/carbon/protocols.py", line 113, in stringReceived
2015-08-05_22:58:28.46735     datapoint = (float(value), float(timestamp))  # force proper types
2015-08-05_22:58:28.46735 exceptions.UnboundLocalError: local variable 'value' referenced before assignment
2015-08-05_22:58:28.46735
2015-08-05_22:58:28.46749 05/08/2015 16:58:28 :: [listener] MetricPickleReceiver connection with 127.0.0.1:58306 lost: local variable 'value' referenced before assignment
2015-08-05_22:58:28.47625 05/08/2015 16:58:28 :: [listener] MetricPickleReceiver connection with 127.0.0.1:58320 established
2015-08-05_22:58:28.48357 05/08/2015 16:58:28 :: [listener] Error decoding pickle: too many values to unpack
2015-08-05_22:58:28.48357 05/08/2015 16:58:28 :: [console] Unhandled Error
```

I've been working around the issue by restarting all the carbon-cache and carbon-relay processes, which usually gets the system to start recording data again.

Thoughts? Please let me know if I can help clarify with more information.

**Comment by deniszh** [comment]
Are you using pickle listener at all btw (port 2004 by default)? Something is throwing some garbage on that port. I only found that Mozilla has some bug because of misconfiguration - https://bugzilla.mozilla.org/show_bug.cgi?id=845860

**Comment by theJohnnyBrown** [comment]
Thanks @deniszh! From reading that report it looks like I should have CARBONLINK_HOSTS set to the CACHE_QUERY_PORT of each of my cache processes, correct? Currently the carbon.conf is set up like,

```
...

[cache:2]
LINE_RECEIVER_PORT = 2023
PICKLE_RECEIVER_PORT = 2024
CACHE_QUERY_PORT = 7022

[cache:3]
LINE_RECEIVER_PORT = 2033
PICKLE_RECEIVER_PORT = 2034
CACHE_QUERY_PORT = 7032

...

[relay]
LINE_RECEIVER_INTERFACE = 0.0.0.0
LINE_RECEIVER_PORT = 2093
PICKLE_RECEIVER_PORT = 2094
RELAY_METHOD = consistent-hashing
USE_FLOW_CONTROL = False
DESTINATIONS = 127.0.0.1:2014:1, 127.0.0.1:2024:2, 127.0.0.1:2034:3, 127.0.0.1:2044:4, 127.0.0.1:2054:5

[relay:cluster]
LINE_RECEIVER_INTERFACE = 0.0.0.0
LINE_RECEIVER_PORT = 2003
PICKLE_RECEIVER_PORT = 2004
RELAY_METHOD = consistent-hashing
USE_FLOW_CONTROL = False
DESTINATIONS = 127.0.0.1:2094:1, 10.3.1.34:2094:1, 10.3.1.35:2094:1, 10.3.1.36:2094:1
REPLICATION_FACTOR = 1
```

with local_settings.py containing

```
CLUSTER_SERVERS = ['localhost:80', '10.3.1.34:80', '10.3.1.35:80', '10.3.1.36:80']
CARBONLINK_HOSTS = ['127.0.0.1:2014:1', '127.0.0.1:2024:2', '127.0.0.1:2034:3', '127.0.0.1:2044:4', '127.0.0.1:2054:5']
```

So yes, it looks like the carbonlink hosts are pointing to the pickle receiver ports. Now I wonder how graphite is showing anything at all.

**Comment by deniszh** [comment]
IIRC if carbonlink request fails it will read data from disk directly.

**Comment by theJohnnyBrown** [comment]
Pointing CARBONLINK_HOSTS to the correct QUERY_PORT solved our problem. Thanks again for your help!
