### ISSUE TITLE
struct.error when sending metrics via TCP (2003)

### ISSUE THREAD

**Issue by asafm-logzio** [graphite-project/carbon#466]
Hi,

When I'm sending data which has a negative value or a big long value I get this error in carbon.log:

```
09/11/2015 13:44:36 :: [console] Unhandled Error
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 207, in _worker
    result = context.call(ctx, function, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
  File "/opt/graphite/lib/carbon/writer.py", line 149, in writeForever
    writeCachedDataPoints()
--- <exception caught here> ---
  File "/opt/graphite/lib/carbon/writer.py", line 128, in writeCachedDataPoints
    whisper.update_many(dbFilePath, datapoints)
  File "/usr/local/lib/python2.7/dist-packages/whisper.py", line 577, in update_many
    return file_update_many(fh, points)
  File "/usr/local/lib/python2.7/dist-packages/whisper.py", line 611, in file_update_many
    __archive_update_many(fh,header,currentArchive,currentPoints)
  File "/usr/local/lib/python2.7/dist-packages/whisper.py", line 631, in __archive_update_many
    currentString += struct.pack(pointFormat,interval,value)
struct.error: 'L' format requires 0 <= number <= 4294967295
```

I solved it by delete the whisper directory.

What exactly happened here? Why was that the only solution?

My graphite version is 0.9.12.

**Comment by obfuscurity** [comment]
Sounds like you're sending metrics with an invalid timestamp. See https://answers.launchpad.net/graphite/+question/261634. If this is not the case please let us know and we can reopen this issue.
