### ISSUE TITLE
carbon aggregator metrics not shown

### ISSUE THREAD

**Issue by heyang930520** [graphite-project/carbon#468]
System version: ubuntu 12.04
graphite version: 0.9.14
Structure: two carbon cache instances, one carbon aggregator.
I used my own wrapper cookbook based on graphite cookbook to install graphite. And I configured nginx working as a proxy in front of uwsgi. After the build, I can visit the website and all the things works fine except that no aggregator metrics show up.
Then I checked the log and found an error.
Error path: `path/to/graphite/storage/log/carbon-aggregator/carbon-aggregator-a/console.log`
```
11/11/2015 16:03:01 :: Log opened.
11/11/2015 16:03:01 :: twistd 13.1.0 (/usr/bin/python 2.7.3) starting up.
11/11/2015 16:03:01 :: reactor class: twisted.internet.epollreactor.EPollReactor.
11/11/2015 16:03:01 :: ServerFactory starting on 2003
11/11/2015 16:03:01 :: Starting factory <twisted.internet.protocol.ServerFactory instance at 0x1bc2e60>
11/11/2015 16:03:01 :: ServerFactory starting on 2004
11/11/2015 16:03:01 :: Starting factory <twisted.internet.protocol.ServerFactory instance at 0x1bd8050>
11/11/2015 16:03:01 :: MetricDatagramReceiver starting on 2003
11/11/2015 16:03:01 :: Starting protocol <carbon.protocols.MetricDatagramReceiver instance at 0x1bd8170>
11/11/2015 16:03:01 :: Starting factory CarbonClientFactory(127.0.0.1:2024:a)
11/11/2015 16:03:01 :: Starting factory CarbonClientFactory(127.0.0.1:2034:b)
11/11/2015 16:04:01 :: Unhandled error in Deferred:
11/11/2015 16:04:01 :: Unhandled Error
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1192, in run
    self.mainLoop()
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
    self.runUntilCurrent()
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 218, in __call__
    d = defer.maybeDeferred(self.f, *self.a, **self.kw)
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 137, in maybeDeferred
    result = f(*args, **kw)
  File "/path/to/graphite/lib/carbon/instrumentation.py", line 119, in recordMetrics
    record('allocatedBuffers', len(carbon.aggregator.buffers.BufferManager))
exceptions.NameError: global name 'carbon' is not defined
```
I checked both master branch and 0.9.x branch, and this line is different in [master](https://github.com/graphite-project/carbon/blob/master/lib/carbon/instrumentation.py#L119).
Anyone knows how this happened and how to solve this problem?
Thanks!

**Comment by deniszh** [comment]
Could you please try replace
https://github.com/graphite-project/carbon/blob/master/lib/carbon/instrumentation.py#L119-L121
with same thing as we have on master -https://github.com/graphite-project/carbon/blob/master/lib/carbon/instrumentation.py#L119-L121:
```python
    record('allocatedBuffers', len(BufferManager))
    record('bufferedDatapoints',
           sum([b.size for b in BufferManager.buffers.values()]))
``` ?

**Comment by heyang930520** [comment]
@deniszh I replace the lines but got similar error.
```
11/11/2015 16:52:39 :: Starting factory CarbonClientFactory(127.0.0.1:2034:b)
11/11/2015 16:53:21 :: Unhandled error in Deferred:
11/11/2015 16:53:21 :: Unhandled Error
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1192, in run
    self.mainLoop()
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
    self.runUntilCurrent()
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 218, in __call__
    d = defer.maybeDeferred(self.f, *self.a, **self.kw)
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 137, in maybeDeferred
    result = f(*args, **kw)
  File "/path/to/graphite/lib/carbon/instrumentation.py", line 119, in recordMetrics
    record('allocatedBuffers', len(BufferManager))
exceptions.NameError: global name 'BufferManager' is not defined
```
I tried replace the whole file as well but got the import error:
```
File "/ebs/graphite/lib/carbon/aggregator/buffers.py", line 106, in <module>
    from carbon import events, state, instrumentation
ImportError: cannot import name instrumentation
```

**Comment by deniszh** [comment]
Please try this version then - https://gist.github.com/deniszh/ee569bf7948d71aead23

**Comment by heyang930520** [comment]
It works! Thanks @deniszh! Will this version replace the one in 0.9.14?

**Comment by deniszh** [comment]
Yes, I'll create a PR. Maybe we need to think about bugfix release...

**Comment by heyang930520** [comment]
Cool, thank you! Waiting for the new release. I'll close this issue.

**Comment by deniszh** [comment]
No need to close yet, I'll close it after merging. Thanks for reporting!
