### ISSUE TITLE
Carbon cache frozen until carbon-cache processes have been restarted

### ISSUE THREAD

**Issue by toni-moreno** [graphite-project/carbon#479]
Hi we have a trouble with carbon-cache.

We have 1 relay  process in front of 4 cache processes.

This log has been taken at 12:37 minutes ( 8 minutes after the last log in the 4 console.log)

````
# tail -f /logs/apps/graphite/carbon-cache-wr03d/console.log
30/11/2015 12:26:56 :: Sorted 573 cache queues in 0.001417 seconds
30/11/2015 12:26:57 :: Sorted 383 cache queues in 0.001266 seconds
30/11/2015 12:26:58 :: Sorted 296 cache queues in 0.001209 seconds
30/11/2015 12:26:58 :: Sorted 120 cache queues in 0.000902 seconds
30/11/2015 12:26:59 :: Sorted 432 cache queues in 0.001293 seconds
30/11/2015 12:26:59 :: Sorted 22 cache queues in 0.000777 seconds
30/11/2015 12:27:00 :: Sorted 131 cache queues in 0.000998 seconds
30/11/2015 12:27:01 :: Sorted 166 cache queues in 0.000814 seconds
30/11/2015 12:27:10 :: Sorted 3404 cache queues in 0.004825 seconds
30/11/2015 12:29:00 :: Sorted 22701 cache queues in 0.066381 seconds
^C
# tail -f /logs/apps/graphite/carbon-cache-wr03a/console.log
30/11/2015 12:26:56 :: Sorted 65 cache queues in 0.000880 seconds
30/11/2015 12:26:57 :: Sorted 342 cache queues in 0.001273 seconds
30/11/2015 12:26:58 :: Sorted 333 cache queues in 0.001258 seconds
30/11/2015 12:26:58 :: Sorted 49 cache queues in 0.000865 seconds
30/11/2015 12:26:59 :: Sorted 377 cache queues in 0.001209 seconds
30/11/2015 12:27:00 :: Sorted 182 cache queues in 0.001087 seconds
30/11/2015 12:27:00 :: Sorted 58 cache queues in 0.000790 seconds
30/11/2015 12:27:01 :: Sorted 424 cache queues in 0.001289 seconds
30/11/2015 12:27:20 :: Sorted 6242 cache queues in 0.009633 seconds
30/11/2015 12:30:10 :: Sorted 21453 cache queues in 0.079278 seconds

^C
# tail -f /logs/apps/graphite/carbon-cache-wr03b/console.log
30/11/2015 12:26:57 :: Sorted 710 cache queues in 0.001553 seconds
30/11/2015 12:26:58 :: Sorted 47 cache queues in 0.000822 seconds
30/11/2015 12:26:59 :: Sorted 213 cache queues in 0.001102 seconds
30/11/2015 12:26:59 :: Sorted 159 cache queues in 0.001001 seconds
30/11/2015 12:26:59 :: Sorted 62 cache queues in 0.000850 seconds
30/11/2015 12:27:00 :: Sorted 287 cache queues in 0.001596 seconds
30/11/2015 12:27:00 :: Sorted 23 cache queues in 0.000827 seconds
30/11/2015 12:27:01 :: Sorted 328 cache queues in 0.001256 seconds
30/11/2015 12:27:11 :: Sorted 4185 cache queues in 0.006936 seconds
30/11/2015 12:29:18 :: Sorted 26946 cache queues in 0.080277 seconds
^C
# tail -f /logs/apps/graphite/carbon-cache-wr03c/console.log
30/11/2015 12:26:56 :: Sorted 513 cache queues in 0.001488 seconds
30/11/2015 12:26:57 :: Sorted 449 cache queues in 0.001367 seconds
30/11/2015 12:26:57 :: Sorted 55 cache queues in 0.000913 seconds
30/11/2015 12:26:58 :: Sorted 310 cache queues in 0.001158 seconds
30/11/2015 12:26:59 :: Sorted 481 cache queues in 0.001652 seconds
30/11/2015 12:26:59 :: Sorted 80 cache queues in 0.000868 seconds
30/11/2015 12:27:00 :: Sorted 197 cache queues in 0.001041 seconds
30/11/2015 12:27:01 :: Sorted 162 cache queues in 0.000960 seconds
30/11/2015 12:27:09 :: Sorted 3027 cache queues in 0.004318 seconds
30/11/2015 12:28:37 :: Sorted 23732 cache queues in 0.081084 seconds
```` 

It seems like a deadlock happens , at 12:28/29 ,  from this time  graphite-web doesn't return data on any render?=xxxx query only error HTTP 500 . ( no error logged in the error.log file).

Any way , after restarted  we have lost 15 minutes of data, 

* There is any way to force flush before restart?

After review the queue length and write time to disc, it seems the origin has not been the IO ( doesn't begins at the same time).

![image](https://cloud.githubusercontent.com/assets/5883405/11471119/40748138-9763-11e5-9d4b-4a56aa18188d.png)

![image](https://cloud.githubusercontent.com/assets/5883405/11471229/2e4a3e48-9764-11e5-9ba0-98157eaf381f.png)

There is any way to locate the bottleneck ?

**Comment by toni-moreno** [comment]
It seems the bottleneck to be in the storage , I/O are becoming worse day to day

**Comment by toni-moreno** [comment]
Each cache process is sorting a lot of queues

[PRO][pmeredbp07].root:~ > tail -f /logs/apps/graphite/carbon-cache-wr07d/console.log
07/12/2015 16:59:27 :: Sorted 29934 cache queues in 0.116829 seconds
07/12/2015 17:00:56 :: Sorted 32542 cache queues in 0.138530 seconds
07/12/2015 17:02:38 :: Sorted 31018 cache queues in 0.089671 seconds
07/12/2015 17:03:50 :: Sorted 31308 cache queues in 0.103204 seconds
07/12/2015 17:04:59 :: Sorted 29484 cache queues in 0.121428 seconds
07/12/2015 17:06:11 :: Sorted 29895 cache queues in 0.057773 seconds
07/12/2015 17:07:10 :: Sorted 31646 cache queues in 0.130335 seconds
07/12/2015 17:07:55 :: Sorted 25141 cache queues in 0.101308 seconds
07/12/2015 17:08:40 :: Sorted 24563 cache queues in 0.041174 seconds
07/12/2015 17:09:36 :: Sorted 31149 cache queues in 0.137492 seconds


![image](https://cloud.githubusercontent.com/assets/5883405/11632034/6f8479cc-9d05-11e5-8d8e-1de6a43317fa.png)


IO Wait is not at 100% 

![image](https://cloud.githubusercontent.com/assets/5883405/11632097/c168411a-9d05-11e5-8262-64eddb504be1.png)

and seems all to be working ok but when queues begin to grow the fact is graphite-web querys to self metrics ( carbon ) , are failing with HTTP 500 and  getting these exceptions.

```

Mon Dec 07 17:17:32 2015 :: Exception encountered in <GET http://10.16.172.192/render/?target=carbon.%2A.graphitehost01%2A.creates&format=pickle&local=1&noCache=1&from=1449483451&until=1449504991>
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/graphite/webapp/graphite/render/views.py", line 112, in renderView
    seriesList = evaluateTarget(requestContext, target)
  File "/opt/graphite/webapp/graphite/render/evaluator.py", line 8, in evaluateTarget
    result = evaluateTokens(requestContext, tokens)
  File "/opt/graphite/webapp/graphite/render/evaluator.py", line 29, in evaluateTokens
    return evaluateTokens(requestContext, tokens.expression, replacements)
  File "/opt/graphite/webapp/graphite/render/evaluator.py", line 45, in evaluateTokens
    return fetchData(requestContext, expression)
  File "/opt/graphite/webapp/graphite/render/datalib.py", line 141, in fetchData
    raise Exception("Failed after %i retry! See: %s" % (settings.MAX_FETCH_RETRIES, e))
Exception: Failed after 2 retry! See: 'float' object is not iterable
````

**Comment by toni-moreno** [comment]
This error seems to be always from carbon metrics.

```` 
grep "Exception encountered in"  /logs/apps/graphite/webapp/exception.log


Mon Dec 07 15:39:43 2015 :: Exception encountered in <GET http://10.16.172.192/render?from=-15min&format=raw&target=carbon.agents.graphitehost01-wr07a.cpuUsage>
Mon Dec 07 15:42:26 2015 :: Exception encountered in <GET http://10.16.172.192/render/?target=carbon.%2A.graphitehost01-wr%2A.cpuUsage&format=pickle&local=1&noCache=1&from=1449477746&until=1449499286>
Mon Dec 07 15:42:26 2015 :: Exception encountered in <GET http://10.16.172.192/render/?target=carbon.%2A.graphitehost01-wr%2A.memUsage&format=pickle&local=1&noCache=1&from=1449477746&until=1449499286>
Mon Dec 07 15:42:27 2015 :: Exception encountered in <GET http://10.16.172.192/render/?target=carbon.%2A.graphitehost01-dist%2A.memUsage&format=pickle&local=1&noCache=1&from=1449477746&until=1449499286>
Mon Dec 07 15:42:27 2015 :: Exception encountered in <GET http://10.16.172.192/render/?target=carbon.%2A.graphitehost01-wr%2A.cache.queues&format=pickle&local=1&noCache=1&from=1449477747&until=1449499287>
Mon Dec 07 15:49:01 2015 :: Exception encountered in <GET http://10.16.172.192/render/?target=carbon.%2A.graphitehost01-wr%2A.memUsage&format=pickle&local=1&noCache=1&from=1449478141&until=1449499681>
Mon Dec 07 15:49:02 2015 :: Exception encountered in <GET http://10.16.172.192/render/?target=carbon.%2A.graphitehost01-wr%2A.cache.queues&format=pickle&local=1&noCache=1&from=1449478142&until=1449499682>
Mon Dec 07 15:49:03 2015 :: Exception encountered in <GET http://10.16.172.192/render/?target=carbon.%2A.graphitehost01-wr%2A.cache.queries&format=pickle&local=1&noCache=1&from=1449478142&until=1449499682>
Mon Dec 07 15:49:03 2015 :: Exception encountered in <GET http://10.16.172.192/render/?target=carbon.%2A.graphitehost01-wr%2A.avgUpdateTime&format=pickle&local=1&noCache=1&from=1449478142&until=1449499682>
Mon Dec 07 15:49:03 2015 :: Exception encountered in <GET http://10.16.172.192/render/?target=carbon.%2A.graphitehost01-wr%2A.metricsReceived&format=pickle&local=1&noCache=1&from=1449478142&until=1449499682>
Mon Dec 07 15:49:03 2015 :: Exception encountered in <GET http://10.16.172.192/render/?target=carbon.relays.graphitehost01%2A.destinations.%2A.relayMaxQueueLength&format=pickle&local=1&noCache=1&from=1449478143&until=1449499683>
Mon Dec 07 15:51:46 2015 :: Exception encountered in <GET http://10.16.172.192/render?from=-15min&format=raw&target=carbon.agents.graphitehost01-wr07a.cpuUsage>
Mon Dec 07 16:23:40 2015 :: Exception encountered in <GET http://10.16.172.192/render/?target=carbon.%2A.graphitehost01-wr%2A.cpuUsage&format=pickle&local=1&noCache=1&from=1449480220&until=1449501760>
Mon Dec 07 16:23:41 2015 :: Exception encountered in <GET http://10.16.172.192/render/?target=carbon.%2A.graphitehost01-wr%2A.metricsReceived&format=pickle&local=1&noCache=1&from=1449480221&until=1449501761>
Mon Dec 07 16:23:42 2015 :: Exception encountered in <GET http://10.16.172.192/render/?target=carbon.%2A.graphitehost01-wr%2A.errors&format=pickle&local=1&noCache=1&from=1449480221&until=1449501761>
Mon Dec 07 16:25:26 2015 :: Exception encountered in <GET http://10.16.172.192/render/?target=carbon.%2A.graphitehost01-wr%2A.cpuUsage&format=pickle&local=1&noCache=1&from=1449480326&until=1449501866>
Mon Dec 07 16:25:27 2015 :: Exception encountered in <GET http://10.16.172.192/render/?target=carbon.%2A.graphitehost01-dist%2A.cpuUsage&format=pickle&local=1&noCache=1&from=1449480326&until=1449501866>
Mon Dec 07 16:25:27 2015 :: Exception encountered in <GET http://10.16.172.192/render/?target=carbon.%2A.graphitehost01-wr%2A.cache.queries&format=pickle&local=1&noCache=1&from=1449480327&until=1449501867>
Mon Dec 07 16:25:28 2015 :: Exception encountered in <GET http://10.16.172.192/render/?target=carbon.%2A.graphitehost01-wr%2A.cache.overflow&format=pickle&local=1&noCache=1&from=1449480327&until=1449501867>
Mon Dec 07 16:27:00 2015 :: Exception encountered in <GET http://10.16.172.192/render/?target=carbon.agents.graphitehost01%2A.memUsage&format=pickle&local=1&noCache=1&from=1449480419&until=1449501959>
Mon Dec 07 16:27:00 2015 :: Exception encountered in <GET http://10.16.172.192/render/?target=carbon.agents.graphitehost01%2A.pointsPerUpdate&format=pickle&local=1&noCache=1&from=1449480420&until=1449501960>
Mon Dec 07 16:27:00 2015 :: Exception encountered in <GET http://10.16.172.192/render/?target=carbon.agents.graphitehost01%2A.avgUpdateTime&format=pickle&local=1&noCache=1&from=1449480420&until=1449501960>
Mon Dec 07 16:27:00 2015 :: Exception encountered in <GET http://10.16.172.192/render/?target=carbon.agents.graphitehost01%2A.metricsReceived&format=pickle&local=1&noCache=1&from=1449480420&until=1449501960>
Mon Dec 07 16:34:36 2015 :: Exception encountered in <GET http://10.16.172.192/render/?target=carbon.agents.graphitehost01%2A.cpuUsage&format=pickle&local=1&noCache=1&from=1449480876&until=1449502416>
Mon Dec 07 16:34:37 2015 :: Exception encountered in <GET http://10.16.172.192/render/?target=carbon.agents.graphitehost01%2A.memUsage&format=pickle&local=1&noCache=1&from=1449480877&until=1449502417>
Mon Dec 07 16:34:38 2015 :: Exception encountered in <GET http://10.16.172.192/render/?target=carbon.agents.graphitehost01%2A.metricsReceived&format=pickle&local=1&noCache=1&from=1449480878&until=1449502418>
Mon Dec 07 16:34:38 2015 :: Exception encountered in <GET http://10.16.172.192/render/?target=carbon.agents.graphitehost01%2A.avgUpdateTime&format=pickle&local=1&noCache=1&from=1449480878&until=1449502418>
Mon Dec 07 16:37:12 2015 :: Exception encountered in <GET http://10.16.172.192/render/?target=carbon.%2A.graphitehost01%2A.creates&format=pickle&local=1&noCache=1&from=1449481032&until=1449502572>
Mon Dec 07 16:49:47 2015 :: Exception encountered in <GET http://10.16.172.192/render/?target=carbon.agents.graphitehost01%2A.cpuUsage&format=pickle&local=1&noCache=1&from=1449481787&until=1449503327>
Mon Dec 07 16:49:47 2015 :: Exception encountered in <GET http://10.16.172.192/render/?target=carbon.agents.graphitehost01%2A.memUsage&format=pickle&local=1&noCache=1&from=1449481787&until=1449503327>
Mon Dec 07 16:49:48 2015 :: Exception encountered in <GET http://10.16.172.192/render/?target=carbon.agents.graphitehost01%2A.metricsReceived&format=pickle&local=1&noCache=1&from=1449481787&until=1449503327>
Mon Dec 07 16:49:48 2015 :: Exception encountered in <GET http://10.16.172.192/render/?target=carbon.agents.graphitehost01%2A.cache.queues&format=pickle&local=1&noCache=1&from=1449481788&until=1449503328>
Mon Dec 07 17:06:01 2015 :: Exception encountered in <GET http://10.16.172.192/render/?target=carbon.agents.graphitehost01%2A.memUsage&format=pickle&local=1&noCache=1&from=1449482761&until=1449504301>
Mon Dec 07 17:07:06 2015 :: Exception encountered in <GET http://10.16.172.192/render/?target=carbon.agents.graphitehost01%2A.cache.queues&format=pickle&local=1&noCache=1&from=1449482826&until=1449504366>
Mon Dec 07 17:07:06 2015 :: Exception encountered in <GET http://10.16.172.192/render/?target=carbon.%2A.graphitehost01%2A.creates&format=pickle&local=1&noCache=1&from=1449482826&until=1449504366>
Mon Dec 07 17:17:31 2015 :: Exception encountered in <GET http://10.16.172.192/render/?target=carbon.agents.graphitehost01%2A.cpuUsage&format=pickle&local=1&noCache=1&from=1449483450&until=1449504990>
Mon Dec 07 17:17:31 2015 :: Exception encountered in <GET http://10.16.172.192/render/?target=carbon.agents.graphitehost01%2A.memUsage&format=pickle&local=1&noCache=1&from=1449483451&until=1449504991>
Mon Dec 07 17:17:31 2015 :: Exception encountered in <GET http://10.16.172.192/render/?target=carbon.agents.graphitehost01%2A.avgUpdateTime&format=pickle&local=1&noCache=1&from=1449483451&until=1449504991>
Mon Dec 07 17:17:32 2015 :: Exception encountered in <GET http://10.16.172.192/render/?target=carbon.agents.graphitehost01%2A.cache.queries&format=pickle&local=1&noCache=1&from=1449483452&until=1449504992>
Mon Dec 07 17:17:32 2015 :: Exception encountered in <GET http://10.16.172.192/render/?target=carbon.%2A.graphitehost01%2A.creates&format=pickle&local=1&noCache=1&from=1449483451&until=1449504991>
Mon Dec 07 17:33:57 2015 :: Exception encountered in <GET http://10.16.172.192/render?from=-15min&format=raw&target=carbon.agents.graphitehost01-wr07a.cpuUsage>
```

**Comment by toni-moreno** [comment]
Currently working with carbon master commit: b80ce915a5e420b46e6972512801491e536db1b6

**Comment by toni-moreno** [comment]
4 carbon -cache with this configuration wr07a, wr07b, wr07c , wr07d 

```

[cache]
LOG_DIR=/logs/apps/graphite
STORAGE_DIR    = /metrics/
USER=carbon
LOCAL_DATA_DIR = %(STORAGE_DIR)s/
ENABLE_LOGROTATE = False
MAX_CACHE_SIZE = inf
MAX_UPDATES_PER_SECOND = 50000
MAX_CREATES_PER_MINUTE = 500
LINE_RECEIVER_INTERFACE = 127.0.0.1
ENABLE_UDP_LISTENER = False
UDP_RECEIVER_INTERFACE = 127.0.0.1
UDP_RECEIVER_PORT = 2003
PICKLE_RECEIVER_INTERFACE = 127.0.0.1
USE_INSECURE_UNPICKLER = False
CACHE_QUERY_INTERFACE = 127.0.0.1
USE_FLOW_CONTROL = True
LOG_UPDATES = False
LOG_CACHE_HITS = False
WHISPER_AUTOFLUSH = False
LOG_LISTENER_CONN_SUCCESS = False

[cache:wr07x]
LINE_RECEIVER_PORT=2013
PICKLE_RECEIVER_PORT = 2014
CACHE_QUERY_PORT = 7002

```

**Comment by toni-moreno** [comment]
It seems that the I/O was the problem in this issue, we would like review more in depth the carbon metrics error, I will close this issue.
