### ISSUE TITLE
on 'send queue is full': exceptions.NameError: global name 'carbon' is not defined

### ISSUE THREAD

**Issue by gretel** [graphite-project/carbon#505]
`aggregator.log`:
`17/12/2015 13:44:52 :: CarbonClientFactory(127.0.0.1:2024:b) send queue is full (1000 datapoints)`

`console.log`:
```
--- <exception caught here> ---
  File "/opt/graphite/lib/carbon/events.py", line 20, in __call__

  File "/opt/graphite/lib/carbon/events.py", line 32, in <lambda>

exceptions.NameError: global name 'carbon' is not defined

17/12/2015 13:44:52 :: Exception in cacheFull event handler: args=() kwargs={}
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 393, in callback
    self._startRunCallbacks(result)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 501, in _startRunCallbacks
    self._runCallbacks()
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 588, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/opt/graphite/lib/carbon/client.py", line 114, in queueFullCallback

--- <exception caught here> ---
  File "/opt/graphite/lib/carbon/events.py", line 20, in __call__

  File "/opt/graphite/lib/carbon/events.py", line 32, in <lambda>

exceptions.NameError: global name 'carbon' is not defined

17/12/2015 13:45:02 :: Exception in cacheFull event handler: args=() kwargs={}
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 393, in callback
    self._startRunCallbacks(result)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 501, in _startRunCallbacks
    self._runCallbacks()
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 588, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/opt/graphite/lib/carbon/client.py", line 114, in queueFullCallback

--- <exception caught here> ---
  File "/opt/graphite/lib/carbon/events.py", line 20, in __call__

  File "/opt/graphite/lib/carbon/events.py", line 32, in <lambda>

exceptions.NameError: global name 'carbon' is not defined
```

version `0.9.14` running on `python-2.7.11` on `ubunut-12.04`. regards

**Comment by obfuscurity** [comment]
Fixed in https://github.com/graphite-project/carbon/commit/6aeb5b94274a36f41a2c32a74753a3d05b0cacc2. Upgrade to 0.9.15.

**Comment by gretel** [comment]
thanks!

**Comment by biancalana** [comment]
I'm facing that even on 0.9.15 tag (https://github.com/graphite-project/carbon/blob/0.9.15/lib/carbon/events.py#L32)

If use carbon.instrumentation the error is:
   exceptions.NameError: global name 'carbon' is not defined

Changing to state.instrumentation the error is:
  exceptions.AttributeError: 'module' object has no attribute 'instrumentation'

**Comment by obfuscurity** [comment]
@biancalana Sorry, that particular issue was caught and fixed post-0.9.15. It's a simple patch though.

https://github.com/graphite-project/carbon/commit/6aeb5b94274a36f41a2c32a74753a3d05b0cacc2

**Comment by biancalana** [comment]
@obfuscurity I'm having problems even using with that version...

23/12/2015 16:20:17 :: Exception in cacheFull event handler: args=() kwargs={}
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 393, in callback
    self._startRunCallbacks(result)
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 501, in _startRunCallbacks
    self._runCallbacks()
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 588, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/opt/graphite/lib/carbon/client.py", line 114, in queueFullCallback
    events.cacheFull()
--- <exception caught here> ---
  File "/opt/graphite/lib/carbon/events.py", line 20, in __call__
    handler(*args, **kwargs)
  File "/opt/graphite/lib/carbon/events.py", line 32, in <lambda>
    cacheFull.addHandler(lambda: state.instrumentation.increment('cache.overflow'))
exceptions.AttributeError: 'module' object has no attribute 'instrumentation'

**Comment by biancalana** [comment]
@obfuscurity can it be reopened or it's better a new issue ?

**Comment by biancalana** [comment]
it's better open a new issue ?

**Comment by gretel** [comment]
@biancalana i'd say it's worth a try :four_leaf_clover:

**Comment by DannyXuEverbridge** [comment]
when I do the work for [6aeb5e9](https://github.com/graphite-project/carbon/commit/6aeb5b94274a36f41a2c32a74753a3d05b0cacc2),the exception stack is:
13/01/2016 10:20:15 :: MetricCache is full: self.size=1000001
13/01/2016 10:20:15 :: Exception in cacheFull event handler: args=() kwargs={}
Traceback (most recent call last):
  File "/opt/graphite/lib/carbon/protocols.py", line 78, in lineReceived
    self.metricReceived(metric, datapoint)
  File "/opt/graphite/lib/carbon/protocols.py", line 64, in metricReceived
    events.metricReceived(metric, datapoint)
  File "/opt/graphite/lib/carbon/events.py", line 20, in __call__
    handler(*args, **kwargs)
  File "/opt/graphite/lib/carbon/cache.py", line 48, in store
    events.cacheFull()
--- <exception caught here> ---
  File "/opt/graphite/lib/carbon/events.py", line 20, in __call__
    handler(*args, **kwargs)
  File "/opt/graphite/lib/carbon/events.py", line 32, in <lambda>
    cacheFull.addHandler(lambda: state.instrumentation.increment('cache.overflow'))
exceptions.AttributeError: 'module' object has no attribute 'instrumentation'

**Comment by kristianpaul** [comment]
I'm having same issue even with the fix (https://github.com/graphite-project/carbon/commit/6aeb5b94274a36f41a2c32a74753a3d05b0cacc2)

11/02/2016 14:51:41 :: Exception in cacheFull event handler: args=() kwargs={}
Traceback (most recent call last):
  File "/usr/lib64/python2.6/site-packages/twisted/internet/defer.py", line 382, in callback
    self._startRunCallbacks(result)
  File "/usr/lib64/python2.6/site-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
    self._runCallbacks()
  File "/usr/lib64/python2.6/site-packages/twisted/internet/defer.py", line 577, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/opt/graphite/lib/carbon/client.py", line 114, in queueFullCallback
    events.cacheFull()
--- <exception caught here> ---
  File "/opt/graphite/lib/carbon/events.py", line 20, in __call__
    handler(*args, **kwargs)
  File "/opt/graphite/lib/carbon/events.py", line 32, in <lambda>
    cacheFull.addHandler(lambda: carbon.instrumentation.increment('cache.overflow'))
exceptions.NameError: global name 'carbon' is not defined

**Comment by gretel** [comment]
@kristianpaul remember to delete the according `.pyc` file.

**Comment by gretel** [comment]
applying https://github.com/graphite-project/carbon/commit/6aeb5b94274a36f41a2c32a74753a3d05b0cacc2 leads to `exceptions.AttributeError: 'module' object has no attribute 'instrumentation'`.
i find this is a critical issues.

**Comment by biancalana** [comment]
me 2, I don't know why this is still closed... Flow control is something expected to work.

**Comment by gretel** [comment]
@obfuscurity kindly pinging in request for assistance

**Comment by obfuscurity** [comment]
If you could please voice your concerns and issues with the "non-fix" in https://github.com/graphite-project/carbon/pull/486 it would be greatly appreciated.

**Comment by gretel** [comment]
@obfuscurity thanks, done
