### ISSUE TITLE
Exception in metricReceived event handler when stopping multiple instances carbon cache

### ISSUE THREAD

**Issue by sbarrier** [graphite-project/carbon#506]
When stopping carbon cache running multiple instances console.log get flooded of exceptions > 3500 in this case.

17/12/2015 06:54:35 :: Received SIGTERM, shutting down.
17/12/2015 06:54:35 :: Stopping factory CarbonClientFactory(127.0.0.1:2074:g)
17/12/2015 06:54:35 :: Stopping factory CarbonClientFactory(127.0.0.1:2084:h)
17/12/2015 06:54:35 :: Stopping factory CarbonClientFactory(127.0.0.1:2044:d)
17/12/2015 06:54:35 :: Stopping factory CarbonClientFactory(127.0.0.1:2024:b)
17/12/2015 06:54:35 :: Stopping factory CarbonClientFactory(127.0.0.1:2054:e)
17/12/2015 06:54:35 :: Stopping factory CarbonClientFactory(127.0.0.1:2014:a)
17/12/2015 06:54:35 :: Exception in metricReceived event handler: args=('servers.dn4-domain_10102.org_apache_hadoop_hbase_regionserver_metrics_RegionServerDynamicStatistics.tbl_user_feed_entries_region_5
8f6fc5d565af36f9620e1f416629678_delete_MaxTime', (1450364074.0, 450.0)) kwargs={}
Traceback (most recent call last):
  File "/usr/lib64/python2.6/site-packages/twisted/internet/tcp.py", line 221, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/usr/lib64/python2.6/site-packages/twisted/protocols/basic.py", line 454, in dataReceived
    self.lineReceived(line)
  File "/usr/lib/python2.6/site-packages/carbon/protocols.py", line 78, in lineReceived
    self.metricReceived(metric, datapoint)
  File "/usr/lib/python2.6/site-packages/carbon/protocols.py", line 64, in metricReceived
    events.metricReceived(metric, datapoint)
--- <exception caught here> ---
  File "/usr/lib/python2.6/site-packages/carbon/events.py", line 20, in __call__
    handler(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/carbon/client.py", line 267, in sendDatapoint
    for destination in self.router.getDestinations(metric):
  File "/usr/lib/python2.6/site-packages/carbon/routers.py", line 78, in getDestinations
    for (count, node) in enumerate(self.ring.get_nodes(key)):
  File "/usr/lib/python2.6/site-packages/carbon/hashing.py", line 42, in get_nodes
    assert self.ring
exceptions.AssertionError: 

17/12/2015 06:54:35 :: Exception in metricReceived event handler: args=('servers.dn4-domain_10102.org_apache_hadoop_hbase_regionserver_metrics_RegionServerDynamicStatistics.tbl_entry_shard-20140811_cf_d_
bt_Data_compactionBlockReadCacheHitCnt', (1450364074.0, 0.0)) kwargs={}
Traceback (most recent call last):
  File "/usr/lib64/python2.6/site-packages/twisted/internet/tcp.py", line 221, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/usr/lib64/python2.6/site-packages/twisted/protocols/basic.py", line 454, in dataReceived
    self.lineReceived(line)
  File "/usr/lib/python2.6/site-packages/carbon/protocols.py", line 78, in lineReceived
    self.metricReceived(metric, datapoint)
  File "/usr/lib/python2.6/site-packages/carbon/protocols.py", line 64, in metricReceived
    events.metricReceived(metric, datapoint)
--- <exception caught here> ---
  File "/usr/lib/python2.6/site-packages/carbon/events.py", line 20, in __call__
    handler(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/carbon/client.py", line 267, in sendDatapoint
    for destination in self.router.getDestinations(metric):
  File "/usr/lib/python2.6/site-packages/carbon/routers.py", line 78, in getDestinations
    for (count, node) in enumerate(self.ring.get_nodes(key)):
  File "/usr/lib/python2.6/site-packages/carbon/hashing.py", line 42, in get_nodes
    assert self.ring
exceptions.AssertionError: 
...
17/12/2015 06:54:36 :: (TCP Port 2004 Closed)
17/12/2015 06:54:36 :: Stopping factory <twisted.internet.protocol.ServerFactory instance at 0x19cc6c8>
17/12/2015 06:54:36 :: (TCP Port 2003 Closed)
17/12/2015 06:54:36 :: Stopping factory <twisted.internet.protocol.ServerFactory instance at 0x19c1878>
17/12/2015 06:54:36 :: Stopping factory CarbonClientFactory(127.0.0.1:2034:c)
17/12/2015 06:54:36 :: Stopping factory CarbonClientFactory(127.0.0.1:2064:f)
17/12/2015 06:54:36 :: Main loop terminated.
17/12/2015 06:54:36 :: Server Shut Down.

**Comment by obfuscurity** [comment]
I believe this was fixed in #507.
