### ISSUE TITLE
Errors in Megacarbon rollup plugin

### ISSUE THREAD

**Issue by rowanu** [graphite-project/carbon#52]
Am sometimes seeing this error:

```
[Fri Dec 21 01:50:45 2012]  node_found :: (<CeresNode[0x21b3940]: statsd.numStats>,)
[Fri Dec 21 01:54:05 2012]  --- Error in node_found event-handler ---
[Fri Dec 21 01:54:05 2012]  Traceback (most recent call last):
  File "bin/ceres-maintenance", line 95, in dispatch
    handler(*args, **kwargs)
  File "/opt/graphite/plugins/maintenance/rollup.py", line 51, in node_found
    do_rollup(node, archive, archives[i+1])
  File "/opt/graphite/plugins/maintenance/rollup.py", line 86, in do_rollup
    coarseValue = aggregate(node, fineDatapoints)
  File "/opt/graphite/plugins/maintenance/rollup.py", line 14, in aggregate
    return float(sum(values)) / len(values) # values is guaranteed to be nonempty
TypeError: unsupported operand type(s) for +: 'float' and 'NoneType'
```

Will look in to it.

**Comment by piotr1212** [comment]
Seems to be fixed a long time ago, closing.
