### ISSUE TITLE
Commit e6664cb breaks Carbon startup

### ISSUE THREAD

**Issue by ybizeul** [graphite-project/carbon#581]
I don't see whisper defined anywhere, when I start carbon, I get the following error :

```
root@adva:/opt/graphite/lib/carbon# /etc/init.d/graphite start
Traceback (most recent call last):
  File "/opt/graphite/bin/carbon-cache.py", line 32, in <module>
    run_twistd_plugin(__file__)
  File "/opt/graphite/lib/carbon/util.py", line 94, in run_twistd_plugin
    config.parseOptions(twistd_options)
  File "/usr/lib/python2.7/dist-packages/twisted/application/app.py", line 604, in parseOptions
    usage.Options.parseOptions(self, options)
  File "/usr/lib/python2.7/dist-packages/twisted/python/usage.py", line 266, in parseOptions
    self.subOptions.parseOptions(rest)
  File "/usr/lib/python2.7/dist-packages/twisted/python/usage.py", line 276, in parseOptions
    self.postOptions()
  File "/opt/graphite/lib/carbon/conf.py", line 245, in postOptions
    if whisper.CAN_FALLOCATE:
NameError: global name 'whisper' is not defined
```

**Comment by ybizeul** [comment]
Adding `import whisper` seems to fix the issue

**Comment by ybizeul** [comment]
Merge Request #582 pending

**Comment by obfuscurity** [comment]
This shouldn't be necessary, will look into it. Note that the 0.9.x branch doesn't require this import.

**Comment by obfuscurity** [comment]
I stand corrected, I must've been looking at the wrong branch. Sorry for letting this regression slip through.
