### ISSUE TITLE
Equal sign not supported in a rewrite rule's pattern

### ISSUE THREAD

**Issue by jeromer** [graphite-project/carbon#620]
Hi there,

Imagine you use the https://github.com/signalfx/collectd-haproxy plugin and sends metrics to graphite.

Graphite will then receive metrics with the following format:

`hosts.lb02-xen01.haproxy.[proxy_name=xxxx,service_name=BACKEND].derive.session_total 0.000000 1484329288.
`

You do not want those ugly brackets in your metric names, so you decide to apply the following rewrite rule:
`^(.*)\.haproxy\.\[proxy_name=(.*),service_name=(.*)\]\.(.*)$ = \1.foo.\2.\3.\4`

And then carbon-aggregator starts to complain : 

> 13/01/2017 18:09:18 :: Exception in metricReceived event handler: args=('hosts.lb02-xen01.haproxy.[proxy_name=xxxx,service_name=BACKEND].derive.denied_request', (1484330958.0, 0.0)) kwargs={}
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 220, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/usr/lib/python2.7/dist-packages/twisted/protocols/basic.py", line 454, in dataReceived
    self.lineReceived(line)
  File "/usr/lib/python2.7/dist-packages/carbon/protocols.py", line 78, in lineReceived
    self.metricReceived(metric, datapoint)
  File "/usr/lib/python2.7/dist-packages/carbon/protocols.py", line 64, in metricReceived
    events.metricReceived(metric, datapoint)
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/carbon/events.py", line 20, in __call__
    handler(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/carbon/aggregator/receiver.py", line 13, in process
    metric = rule.apply(metric)
  File "/usr/lib/python2.7/dist-packages/carbon/rewrite.py", line 72, in apply
    return self.regex.sub(self.replacement, metric)
  File "/usr/lib/python2.7/re.py", line 291, in filter
    return sre_parse.expand_template(template, match)
  File "/usr/lib/python2.7/sre_parse.py", line 813, in expand_template
    raise error, "invalid group reference"
sre_constants.error: invalid group reference

This is because of the following line : https://github.com/graphite-project/carbon/blob/master/lib/carbon/aggregator/rules.py#L56 where the split on "=" actually ends up with a completely broken pattern when the pattern contains "="

:)

**Comment by jeromer** [comment]
Using the octal value of "=" works though.

For example : `^(.*)\.haproxy\.\[proxy_name\075(.*),service_name\075(.*)\]\.(.*)$ = \1.haproxy.\2.\3.\4
`

**Comment by jeromer** [comment]
Actually this is not a bug but more a confusing lack of documentation.

If we wanted to fix the problem by patching the code the following options would be available:

1. support `\=` so we could write `a\=b = whatever` but this will be even more confusing because `\=` does not exist in regular expression syntax. So we end up mixing regular expression standard syntax and extra characters. This does not work.

2. splitting text on the last available `=` but this does not work either if the rewrite rule looks like `foo=a.b = c.d`

It is not automatic for people to say "hey I can use the octal notation of a character in regular expressions" to fix my problem.

So this "bug" could be easily "fixed" by a not in [the documentation](http://graphite.readthedocs.io/en/latest/config-carbon.html#rewrite-rules-conf) saying something like

> Note: if you plan to use the '=' sign in your rewrite rules. Use its octal value : \075. For example "foo=bar = foo.bar" would be foo\075bar = foo.bar

And that's it :)
