### ISSUE TITLE
CACHE_WRITE_STRATEGY fix in #628 breaks MetricCache()

### ISSUE THREAD

**Issue by deniszh** [graphite-project/carbon#633]
Before #628 cache.MetricCache() was instance of dict-derived _MetricCache class, but after it's a function - https://github.com/graphite-project/carbon/blob/d0c3c31b75777039ad74d6bf6443e282d7a7ba02/lib/carbon/cache.py#L204
It brings at least one error:
```
01/03/2017 09:13:22 :: Unhandled Error
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/posixbase.py", line 597, in _doReadOrWrite
    why = selectable.doRead()
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 208, in doRead
    return self._dataReceived(data)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 214, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/usr/local/lib/python2.7/dist-packages/twisted/protocols/basic.py", line 765, in dataReceived
    self.stringReceived(packet)
  File "/opt/graphite/lib/carbon/protocols.py", line 202, in stringReceived
    datapoints = MetricCache.get(metric, {}).items()
exceptions.AttributeError: 'function' object has no attribute 'get'
```
I'm suspecting that can cause another issue e.g. in https://github.com/graphite-project/carbon/blob/abff76a3962515003961f40f9e5fd8a3a28ed5c6/lib/carbon/instrumentation.py#L95

**Comment by deniszh** [comment]
@iksaif - please note ☝️

**Comment by iksaif** [comment]
Linked PR

**Comment by deniszh** [comment]
Fixed
