### ISSUE TITLE
Carbon doesn't install properly or start 

### ISSUE THREAD

**Issue by kira510** [graphite-project/carbon#660]
When i try 

pip install carbon==0.9.15 ,

i get the below error. 
`for migrate carbon
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 283, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1436, in install
    requirement.install(install_options, global_options, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 672, in install
    self.move_wheel_files(self.source_dir, root=root)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 902, in move_wheel_files
    pycompile=self.pycompile,
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 206, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 193, in clobber
    os.makedirs(destsubdir)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/constantly-15.1.0.dist-info'

Storing debug log for failure in /tmp/tmpSZGJ0z`

And when i try to run my carbon cache instance, i get the error
` $ carbon-cache.py --instance=1 start
   Traceback (most recent call last):
  File "/opt/graphite/bin/carbon-cache.py", line 28, in <module>
    from carbon.util import run_twistd_plugin
  File "/opt/graphite/lib/carbon/util.py", line 20, in <module>
    from twisted.python.util import initgroups
  File "/opt/graphite/lib/twisted/__init__.py", line 23, in <module>
    from twisted._version import __version__ as version
  File "/opt/graphite/lib/twisted/_version.py", line 8, in <module>
    from incremental import Version
ImportError: No module named incremental
`

Any idea?

Thanks for the help in advance.
Kiran

**Comment by piotr1212** [comment]
> OSError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/constantly-15.1.0.dist-info'

Seems to be permission error. Set correct permissions or just run as root or with sudo:
`sudo pip install carbon==0.9.15`

ps. 0.9.15 is not the latest version version. If you can use a the latest version.

**Comment by kira510** [comment]
Thanks for the quick reply, will get back to as soon as possible.
