### ISSUE TITLE
Exception in cacheFull event handler

### ISSUE THREAD

**Issue by cflinspach** [graphite-project/carbon#690]
I installed graphite-carbon from apt and we're getting the error from #516 . I edited service.py to match the fix from #534 and we're still getting the issue. 

/usr/lib/python2.7/dist-packages/carbon/service.py

```
from os.path import exists

from twisted.application.service import MultiService
from twisted.application.internet import TCPServer, TCPClient, UDPServer
from twisted.internet.protocol import ServerFactory
from twisted.python.components import Componentized
from twisted.python.log import ILogObserver
# Attaching modules to the global state module simplifies import order hassles
from carbon import state, util, events, instrumentation
from carbon.log import carbonLogObserver
from carbon.exceptions import CarbonConfigException
state.instrumentation = instrumentation
```

Error:
```
13/10/2017 10:13:08 :: MetricCache is full: self.size=5000002
13/10/2017 10:13:08 :: Exception in cacheFull event handler: args=() kwargs={}
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/carbon/protocols.py", line 78, in lineReceived
    self.metricReceived(metric, datapoint)
  File "/usr/lib/python2.7/dist-packages/carbon/protocols.py", line 64, in metricReceived
    events.metricReceived(metric, datapoint)
  File "/usr/lib/python2.7/dist-packages/carbon/events.py", line 20, in __call__
    handler(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/carbon/cache.py", line 48, in store
    events.cacheFull()
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/carbon/events.py", line 20, in __call__
    handler(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/carbon/events.py", line 32, in <lambda>
    cacheFull.addHandler(lambda: carbon.instrumentation.increment('cache.overflow'))
exceptions.NameError: global name 'carbon' is not defined
```
```
apt-show-versions graphite-carbon
graphite-carbon:all/xenial 0.9.15-1 uptodate
```
Edit: Applied the fix from #505 and now I don't get any errors in console.log, but once the MetricCache is full it just fills the log with:

```
13/10/2017 11:10:41 :: MetricCache is full: self.size=3000178
13/10/2017 11:10:41 :: MetricCache is full: self.size=3000179
13/10/2017 11:10:41 :: MetricCache is full: self.size=3000180
13/10/2017 11:10:41 :: MetricCache is full: self.size=3000181
13/10/2017 11:10:41 :: MetricCache is full: self.size=3000182
13/10/2017 11:10:41 :: MetricCache is full: self.size=3000183
13/10/2017 11:10:41 :: MetricCache is full: self.size=3000184
13/10/2017 11:10:41 :: MetricCache is full: self.size=3000185
13/10/2017 11:10:41 :: MetricCache is full: self.size=3000186
13/10/2017 11:10:41 :: MetricCache is full: self.size=3000187
13/10/2017 11:10:41 :: MetricCache is full: self.size=3000188
13/10/2017 11:10:41 :: MetricCache is full: self.size=3000189
13/10/2017 11:10:41 :: MetricCache is full: self.size=3000190
13/10/2017 11:10:41 :: MetricCache is full: self.size=3000191
13/10/2017 11:10:41 :: MetricCache is full: self.size=3000192
13/10/2017 11:10:41 :: MetricCache is full: self.size=3000193
13/10/2017 11:10:41 :: MetricCache is full: self.size=3000194
13/10/2017 11:10:41 :: MetricCache is full: self.size=3000195
13/10/2017 11:10:41 :: MetricCache is full: self.size=3000196
13/10/2017 11:10:41 :: MetricCache is full: self.size=3000197
13/10/2017 11:10:41 :: MetricCache is full: self.size=3000198
13/10/2017 11:10:41 :: MetricCache is full: self.size=3000199
13/10/2017 11:10:41 :: MetricCache is full: self.size=3000200
```

My /usr/lib/python2.7/dist-packages/carbon/events.py
```
metricReceived = Event('metricReceived')
metricGenerated = Event('metricGenerated')
cacheFull = Event('cacheFull')
cacheSpaceAvailable = Event('cacheSpaceAvailable')
pauseReceivingMetrics = Event('pauseReceivingMetrics')
resumeReceivingMetrics = Event('resumeReceivingMetrics')

cacheFull.addHandler(lambda: state.instrumentation.increment('cache.overflow'))
cacheFull.addHandler(lambda: setattr(state, 'cacheTooFull', True))
cacheSpaceAvailable.addHandler(lambda: setattr(state, 'cacheTooFull', False))

pauseReceivingMetrics.addHandler(lambda: setattr(state, 'metricReceiversPaused', True))
resumeReceivingMetrics.addHandler(lambda: setattr(state, 'metricReceiversPaused', False))
```

**Comment by deniszh** [comment]
Hi @cflinspach,
if your metric cache is full - you should increase it, or scale up graphite caches.
Also, graphite 0.9.15 is quite old and outdated.

**Comment by cflinspach** [comment]
@deniszh I've set my MAX_CACHE_SIZE to inf and tried values for MAX_UPDATES_PER_SECOND ranging from the very small (200) to large (1000, 10000,100000 and more values in between) and many_updates never seemed to kick in. The cache would just grow and grow but we consistently saw under 5k update operations with only 1 or 2 points per update. our cache was set low to reproduce this error. 

Since Friday though we've tried upgrading to 1.10 by installing from source with:
`python setup.py install --install-scripts=/usr/bin --install-lib=/usr/lib/python2.7/dist-packages --install-data=/var/lib/graphite` for Graphite-web, Carbon, Ceres, and Whisper.

Now we're seeing different problems. When Carbon-cache starts console.log shows:

```
16/10/2017 07:13:52 :: Starting factory <twisted.web.client._HTTP11ClientFactory instance at 0x7f1beb24b3b0>
16/10/2017 07:13:53 :: Tagging icinga2.services.All_Interface_Status.snmp-all-interfaces.perfdata.If_Summit200-24-Port_25.check_interface_table_port.BpsIn.value
16/10/2017 07:13:53 :: Starting factory <twisted.web.client._HTTP11ClientFactory instance at 0x7f1beb24b8c0>
16/10/2017 07:13:53 :: Tagging icinga2.services.All_Interface_Status.snmp-all-interfaces.perfdata.If_FastEthernet0_6.check_interface_table_port.PpsOutErr.value
16/10/2017 07:13:53 :: Starting factory <twisted.web.client._HTTP11ClientFactory instance at 0x7f1beb24bdd0>
16/10/2017 07:13:53 :: Tagging icinga2.services.All_Interface_Status.snmp-all-interfaces.perfdata.Interface_global.check_interface_table_global.freeports.value
16/10/2017 07:13:53 :: Starting factory <twisted.web.client._HTTP11ClientFactory instance at 0x7f1beb778290>
16/10/2017 07:13:53 :: Tagging icinga2.services.All_Interface_Status.snmp-all-interfaces.perfdata.If_VLAN_00006_CoreSvc.check_interface_table_port.PpsOutDiscard.value
16/10/2017 07:13:53 :: Starting factory <twisted.web.client._HTTP11ClientFactory instance at 0x7f1beb778830>
16/10/2017 07:13:53 :: Tagging icinga2.services.All_Interface_Status.snmp-all-interfaces.perfdata.If_FastEthernet0_42.check_interface_table_port.OperStatus.value
16/10/2017 07:13:53 :: Starting factory <twisted.web.client._HTTP11ClientFactory instance at 0x7f1beb778d40>
16/10/2017 07:13:53 :: Tagging icinga2.services.All_Interface_Status.snmp-all-interfaces.perfdata.If_802.1Q_Encapsulation_Tag_0024.check_interface_table_port.PpsOutDiscard.value
16/10/2017 07:13:53 :: Starting factory <twisted.web.client._HTTP11ClientFactory instance at 0x7f1beb1d8200>
16/10/2017 07:13:53 :: Tagging icinga2.services.All_Interface_Status.snmp-all-interfaces.perfdata.If_FastEthernet0_48.check_interface_table_port.BpsIn.value
16/10/2017 07:13:53 :: Starting factory <twisted.web.client._HTTP11ClientFactory instance at 0x7f1beb1d8680>
16/10/2017 07:13:53 :: Tagging icinga2.services.All_Interface_Status.snmp-all-interfaces.perfdata.If_802.1Q_Encapsulation_Tag_0119.check_interface_table_port.PpsOutDiscard.value
16/10/2017 07:13:53 :: Starting factory <twisted.web.client._HTTP11ClientFactory instance at 0x7f1beb1d8b00>
16/10/2017 07:13:54 :: Tagging icinga2.services.All_Interface_Status.snmp-all-interfaces.perfdata.If_Summit200-24-Port_20.check_interface_table_port.BpsOut.value
16/10/2017 07:13:54 :: Starting factory <twisted.web.client._HTTP11ClientFactory instance at 0x7f1beb1d8f80>
16/10/2017 07:13:54 :: Tagging icinga2.services.All_Interface_Status.snmp-all-interfaces.perfdata.If_Summit200-24-Port_7.check_interface_table_port.PpsOutDiscard.value
```

Then it cascades with: 
```
16/10/2017 08:17:35 :: Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 825, in runUntilCurrent
    
  File "/usr/lib/python2.7/dist-packages/carbon/writer.py", line 149, in writeForever
    
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1274, in unwindGenerator
    
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1128, in _inlineCallbacks
    
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/carbon/writer.py", line 103, in writeCachedDataPoints
    
  File "/usr/lib/python2.7/dist-packages/carbon/database.py", line 140, in create
    
  File "/usr/lib/python2.7/dist-packages/whisper.py", line 503, in create
    
exceptions.IOError: [Errno 24] Too many open files: '/var/lib/graphite/whisper/icinga2/services/All_I
nterface_Status/snmp-all-interfaces/perfdata/If_rif1/check_interface_table_port/PpsOutErr/value.wsp'

16/10/2017 08:17:35 :: Error creating icinga2.0378-SW-ER-11.services.All_Interface_Status.snmp-all-interfaces.perfd
ata.If_rif1.check_interface_table_port.PpsOutErr.value: [Errno 24] Too many open files: '/var/lib/graphite/whisper/
icinga2/0378-SW-ER-11/services/All_Interface_Status/snmp-all-interfaces/perfdata/If_rif1/check_interface_table_port
/PpsOutErr/value.wsp'
```
Here's our ulimit:
```
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 128533
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 5000
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 128533
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```

Currently our max cache is 5mil and max updates set to 3000. We get an average of 600k metrics.

**Comment by deniszh** [comment]
Sorry, @cflinspach, I'm a little bit lost here - does it works now?
You should have some sane values for cache size and max updates, then cache size should stabilize on some value. 5000 man open files are also quite small, try to increase it to 16384.
Please also note that also probably your load is too big for single carbon cache - then you need to put 2-4-etc caches on a single server and balance load with carbon relay or switch to Go-implementation of carbon - https://github.com/lomik/go-carbon

**Comment by cflinspach** [comment]
@deniszh Thanks for your support. It seems that the errors and issues only happen when Carbon is calling many_updates() or flushing the cache. It never seems to write to the disk and our disks never seem taxed.

The flow of it right now is when we start carbon-cache we get alot of those  "Starting factory". This causes alot of sockets to open (3522 is our carbon pid):

```
ls -l /proc/3522/fd/ | head
total 0
lrwx------ 1 root root 64 Oct 16 10:21 0 -> /dev/null
lrwx------ 1 root root 64 Oct 16 10:21 1 -> /dev/null
l-wx------ 1 root root 64 Oct 16 10:21 10 -> pipe:[24067]
lrwx------ 1 root root 64 Oct 16 10:21 100 -> socket:[22160]
lrwx------ 1 root root 64 Oct 16 10:21 101 -> socket:[22161]
lrwx------ 1 root root 64 Oct 16 10:21 102 -> socket:[22162]
lrwx------ 1 root root 64 Oct 16 10:21 103 -> socket:[22163]
lrwx------ 1 root root 64 Oct 16 10:21 104 -> socket:[22164]
lrwx------ 1 root root 64 Oct 16 10:21 105 -> socket:[22165]
```

Then when `ls -l /proc/3522/fd/ | wc -l` is 1025, we console.log is flooded with:
```
16/10/2017 08:17:35 :: Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 825, in runUntilCurrent
    
  File "/usr/lib/python2.7/dist-packages/carbon/writer.py", line 149, in writeForever
    
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1274, in unwindGenerator
    
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1128, in _inlineCallbacks
    
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/carbon/writer.py", line 103, in writeCachedDataPoints
    
  File "/usr/lib/python2.7/dist-packages/carbon/database.py", line 140, in create
    
  File "/usr/lib/python2.7/dist-packages/whisper.py", line 503, in create
    
exceptions.IOError: [Errno 24] Too many open files: '/var/lib/graphite/whisper/icinga2/services/All_I
nterface_Status/snmp-all-interfaces/perfdata/If_rif1/check_interface_table_port/PpsOutErr/value.wsp'

16/10/2017 08:17:35 :: Error creating icinga2.services.All_Interface_Status.snmp-all-interfaces.perfd
ata.If_rif1.check_interface_table_port.PpsOutErr.value: [Errno 24] Too many open files: '/var/lib/graphite/whisper/
icinga2/services/All_Interface_Status/snmp-all-interfaces/perfdata/If_rif1/check_interface_table_port
/PpsOutErr/value.wsp'
```
and carbon dies without writing anything to disk.

**Comment by cflinspach** [comment]
This is what we're seeing before it crashes,
![screenshot from 2017-10-16 10-28-01](https://user-images.githubusercontent.com/4700533/31625947-c580f8fa-b25c-11e7-970d-311caba6b7c4.png)

And here's it after,
![screenshot from 2017-10-16 10-30-19](https://user-images.githubusercontent.com/4700533/31626034-101fa1ea-b25d-11e7-92ef-1b318654f22a.png)

**Comment by cflinspach** [comment]
Also I don't know if this is relevant but when we install carbon from source it outputs this:

```
python setup.py install --install-scripts=/usr/bin --install-lib=/usr/lib/python2.7/dist-packages --install-data=/var/lib/graphite
################################################################################

Carbon's default installation prefix is "/opt/graphite".

To install Carbon in the Python's default location run:
$ GRAPHITE_NO_PREFIX=True python setup.py install

################################################################################
/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
running install
running build
running build_py
package init file 'lib/twisted/plugins/__init__.py' not found (or not a regular file)
package init file 'lib/twisted/plugins/__init__.py' not found (or not a regular file)
running build_scripts
running install_lib
running install_scripts
changing mode of /usr/bin/carbon-client.py to 755
changing mode of /usr/bin/carbon-aggregator.py to 755
changing mode of /usr/bin/validate-storage-schemas.py to 755
changing mode of /usr/bin/carbon-relay.py to 755
changing mode of /usr/bin/carbon-cache.py to 755
changing mode of /usr/bin/carbon-aggregator-cache.py to 755
running install_data
running install_egg_info
Removing /usr/lib/python2.7/dist-packages/carbon-1.1.0-py2.7.egg-info
Writing /usr/lib/python2.7/dist-packages/carbon-1.1.0-py2.7.egg-info
```
And whisper
```
python setup.py install --install-scripts=/usr/bin --install-lib=/usr/lib/python2.7/dist-packages --install-data=/var/lib/graphite
/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
running install
running build
running build_py
running build_scripts
running install_lib
running install_scripts
changing mode of /usr/bin/whisper-diff.py to 755
changing mode of /usr/bin/whisper-auto-update.py to 755
changing mode of /usr/bin/whisper-merge.py to 755
changing mode of /usr/bin/whisper-fetch.py to 755
changing mode of /usr/bin/whisper-auto-resize.py to 755
changing mode of /usr/bin/whisper-update.py to 755
changing mode of /usr/bin/update-storage-times.py to 755
changing mode of /usr/bin/whisper-info.py to 755
changing mode of /usr/bin/find-corrupt-whisper-files.py to 755
changing mode of /usr/bin/whisper-fill.py to 755
changing mode of /usr/bin/whisper-set-aggregation-method.py to 755
changing mode of /usr/bin/whisper-create.py to 755
changing mode of /usr/bin/whisper-dump.py to 755
changing mode of /usr/bin/rrd2whisper.py to 755
changing mode of /usr/bin/whisper-resize.py to 755
changing mode of /usr/bin/whisper-set-xfilesfactor.py to 755
running install_egg_info
Removing /usr/lib/python2.7/dist-packages/whisper-1.1.0.egg-info
Writing /usr/lib/python2.7/dist-packages/whisper-1.1.0.egg-info

```

**Comment by deniszh** [comment]
Hi Casey,

You should increase max number of open files to at least 16384 - then
errors should gone.
Your installation is not a tiny one - you should tune your system for
additional load.

**Comment by cflinspach** [comment]
@deniszh It's at 16384 and we're still not writing data. We see this in the logs now in big chunks and after all the sockets are gone from proc/<pid>/fd. 

```
16/10/2017 12:21:52 :: Stopping factory <twisted.web.client._HTTP11ClientFactory instance at 0x7f01eaf95830>
16/10/2017 12:21:52 :: Error tagging icinga2.services.All_Interface_Status.snmp-all-interfaces.per
fdata.If_X150-48t_Port_33.check_interface_table_port.BpsOut.value: [Failure instance: Traceback (failure with no fr
ames): <class 'twisted.internet.error.TimeoutError'>: User timeout caused connection failure.
]
16/10/2017 12:21:52 :: Stopping factory <twisted.web.client._HTTP11ClientFactory instance at 0x7f01eaf96ea8>
16/10/2017 12:21:52 :: Error tagging icinga2.services.All_Interface_Status.snmp-all-interfaces.perfda
ta.If_802.1Q_Encapsulation_Tag_0126.check_interface_table_port.OperStatus.value: [Failure instance: Traceback (fail
ure with no frames): <class 'twisted.internet.error.TimeoutError'>: User timeout caused connection failure.
]
16/10/2017 12:21:52 :: Stopping factory <twisted.web.client._HTTP11ClientFactory instance at 0x7f01eaf94fc8>
16/10/2017 12:21:52 :: Error tagging icinga2.services.All_Interface_Status.snmp-all-interfaces.perfd
ata.If_Summit200-48-Port_25.check_interface_table_port.BpsOut.value: [Failure instance: Traceback (failure with no 
frames): <class 'twisted.internet.error.TimeoutError'>: User timeout caused connection failure.
]
16/10/2017 12:21:52 :: Stopping factory <twisted.web.client._HTTP11ClientFactory instance at 0x7f01eaf956c8>
16/10/2017 12:21:52 :: Error tagging icinga2.services.All_Interface_Status.snmp-all-interfaces.pe
rfdata.Interface_global.check_interface_table_global.uptime.value: [Failure instance: Traceback (failure with no fr
ames): <class 'twisted.internet.error.TimeoutError'>: User timeout caused connection failure.
]
16/10/2017 12:21:52 :: Stopping factory <twisted.web.client._HTTP11ClientFactory instance at 0x7f01eaf927e8>
16/10/2017 12:21:52 :: Error tagging icinga2.services.All_Interface_Status.snmp-all-interfaces.p
erfdata.If_VLAN_00012_vlan20.check_interface_table_port.BpsOut.value: [Failure instance: Traceback (failure with no
 frames): <class 'twisted.internet.error.TimeoutError'>: User timeout caused connection failure.
]
16/10/2017 12:21:52 :: Stopping factory <twisted.web.client._HTTP11ClientFactory instance at 0x7f01eaf92290>
16/10/2017 12:21:52 :: Error tagging icinga2.services.All_Interface_Status.snmp-all-interfaces.per
fdata.If_VLAN_04095_Mgmt.check_interface_table_port.PpsOutErr.value: [Failure instance: Traceback (failure with no 
frames): <class 'twisted.internet.error.TimeoutError'>: User timeout caused connection failure.
]
16/10/2017 12:21:52 :: Stopping factory <twisted.web.client._HTTP11ClientFactory instance at 0x7f01eaf90d40>
16/10/2017 12:21:52 :: Error tagging icinga2.services.All_Interface_Status.snmp-all-interfaces.pe
rfdata.If_802.1Q_Encapsulation_Tag_0024.check_interface_table_port.BpsIn.value: [Failure instance: Traceback (failu
re with no frames): <class 'twisted.internet.error.TimeoutError'>: User timeout caused connection failure.
```
We'd love to tune our system, this is how it was working prior to the first bug started happening. It worked great, but now we can't get any data to fine tune. 

![screenshot from 2017-10-16 12-29-18](https://user-images.githubusercontent.com/4700533/31631153-a9fbedcc-b26d-11e7-9b21-bd44c5cf056f.png)

**Comment by deniszh** [comment]
The first bug was not a real bug - your cache just become full but prior to #505 you get that error instead of "MetricCache is full". You can revert to 0.9.15 if you want. 
But your graph looks not really well, indeed - your PPU is extremely low for some reason.
Could you please share your configs and some details about your system? You can do that privately, if you want - send it to denis.zhdanov@gmail.com

**Comment by cflinspach** [comment]
This issue was due to a single carbon-cache process being overwhelmed. The resolution is to setup carbon-relay.
