### ISSUE TITLE
Cannot Start Carbon-cache with error

### ISSUE THREAD

**Issue by imanuell** [graphite-project/carbon#762]
04/04/2018 12:00:06 :: Failed to reload storage SCHEMAS
04/04/2018 12:00:06 :: Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1203, in mainLoop
    self.runUntilCurrent()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 825, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/task.py", line 239, in __call__
    d = defer.maybeDeferred(self.f, *self.a, **self.kw)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/carbon/writer.py", line 167, in reloadStorageSchemas
    SCHEMAS = loadStorageSchemas()
  File "/usr/lib/python2.7/dist-packages/carbon/storage.py", line 125, in loadStorageSchemas
    retentions = options['retentions'].split(',')
exceptions.KeyError: 'retentions'

**Comment by deniszh** [comment]
Yes, that's known. Having a proper schema is vital for running carbon.

**Comment by imanuell** [comment]
already fix it.
after do some editing the retention in storage-schemas 
all i need is review the schema and use retention in every schema
