### ISSUE TITLE
[console] Unhandled Error

### ISSUE THREAD

**Issue by flowppp** [graphite-project/carbon#766]
Hi All,

I have this error message when my carbon-relay is working : 

16/04/2018 09:34:28 :: [console] Unhandled Error
Traceback (most recent call last):
  File "/opt/programs/graphite/lib64/python3.4/site-packages/twisted/protocols/basic.py", line 454, in dataReceived
    self.lineReceived(line)
  File "/opt/programs/graphite/lib64/python3.4/site-packages/carbon/protocols.py", line 179, in lineReceived
    self.metricReceived(metric, datapoint)
  File "/opt/programs/graphite/lib64/python3.4/site-packages/carbon/protocols.py", line 157, in metricReceived
    events.metricReceived(metric, datapoint)
  File "/opt/programs/graphite/lib64/python3.4/site-packages/carbon/events.py", line 17, in __call__
    handler(*args, **kwargs)
--- <exception caught here> ---
  File "/opt/programs/graphite/lib64/python3.4/site-packages/carbon/pipeline.py", line 31, in run_pipeline
    for out_metric, out_datapoint in processor.process(metric, datapoint):
  File "/opt/programs/graphite/lib64/python3.4/site-packages/carbon/client.py", line 569, in process
    state.client_manager.sendDatapoint(metric, datapoint)
  File "/opt/programs/graphite/lib64/python3.4/site-packages/carbon/client.py", line 554, in sendDatapoint
    for destination in self.getDestinations(metric):
  File "/opt/programs/graphite/lib64/python3.4/site-packages/carbon/client.py", line 546, in getDestinations
    destinations = list(self.router.getDestinations(metric))
  File "/opt/programs/graphite/lib64/python3.4/site-packages/carbon/routers.py", line 108, in getDestinations
    for (server, instance) in self.ring.get_nodes(key):
  File "/opt/programs/graphite/lib64/python3.4/site-packages/carbon/hashing.py", line 108, in get_nodes
    index = bisect.bisect_left(self.ring, search_entry) % self.ring_len
builtins.TypeError: unorderable types: tuple() < NoneType()

I have absolutly no idea what's can be.

Thanks for your help
Flo

**Comment by piotr1212** [comment]
Could you please post your carbon.conf?

**Comment by flowppp** [comment]
i'am using python 3.4

**Comment by piotr1212** [comment]
When does this happen? Is there some specific data (in the metricname) that triggers this?

**Comment by flowppp** [comment]
Directly when i start carbon-relay and it is very often(it can be every seconds for 1mn). in the carbon-relay debug log i have no indication about the metric name.

**Comment by DanCech** [comment]
The problem is that in python 3 you cannot compare None with scalar values like you can in 2
```
$ python3
Python 3.5.2 (default, Nov 23 2017, 16:37:01)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> t = [(1,'1')]
>>> import bisect
>>> bisect.bisect_left(t,(1,None))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unorderable types: str() < NoneType()
...
$ python2
Python 2.7.12 (default, Dec  4 2017, 14:50:18)
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> t = [(1,'1')]
>>> import bisect
>>> bisect.bisect_left(t,(1,None))
0
```
So, we need to update `get_node` and `get_nodes` in `ConsistentHashRing` to not use `None`

**Comment by flowppp** [comment]
Sorry for this dumb question...what is the result of this bug on the collect?

In Any case Thanks a lot guys!!!

**Comment by deniszh** [comment]
> So, we need to update get_node and get_nodes in ConsistentHashRing to not use None

Will it break cache order (I mean compatibiltity with old versions and/or python 2)?

**Comment by deniszh** [comment]
Will try to check

**Comment by deniszh** [comment]
@flowppp 
> Sorry for this dumb question...what is the result of this bug on the collect?

IMO it will break hashing, not sure if relay will work w/o it. It's better not to run it with python3 until it fixed.

**Comment by piotr1212** [comment]
I remember to run into this and had it fixed already

**Comment by DanCech** [comment]
Possible there was a regression in the code to sync the implementation with the one in graphite-web

**Comment by piotr1212** [comment]
Yup I see, I fixed it here:
https://github.com/graphite-project/carbon/commit/7516cf148c5d75c2cd066c32ad95f5d617cca2f0#diff-1486787206e06af358b8d935577e76f5L53

Then it got reverted by syncing code with graphite-web

https://github.com/graphite-project/carbon/commit/fe668a7d920459a139b723b127fee40e2a03bdfc#diff-1486787206e06af358b8d935577e76f5L88

We really should get that code deduplicated
