### ISSUE TITLE
carbon util.py error

### ISSUE THREAD

**Issue by naveenlj** [graphite-project/carbon#773]
Getting below error while trying to start carbon-cache, carbon-cache current logs.
2018-05-11_13:25:42.11772 Starting carbon-cache (instance a)
2018-05-11_13:25:42.11774 Traceback (most recent call last):
2018-05-11_13:25:42.11775   File "/opt/graphite/bin/carbon-cache.py", line 32, in <module>
2018-05-11_13:25:42.11775     run_twistd_plugin(__file__)
2018-05-11_13:25:42.11775   File "/opt/graphite/lib/carbon/util.py", line 132, in run_twistd_plugin
2018-05-11_13:25:42.11775     runApp(config)
2018-05-11_13:25:42.11775   File "/usr/lib64/python2.7/site-packages/twisted/scripts/twistd.py", line 25, in runApp
2018-05-11_13:25:42.11775     runner.run()
2018-05-11_13:25:42.11775   File "/usr/lib64/python2.7/site-packages/twisted/application/app.py", line 381, in run
2018-05-11_13:25:42.11776     self.application = self.createOrGetApplication()
2018-05-11_13:25:42.11776   File "/usr/lib64/python2.7/site-packages/twisted/application/app.py", line 448, in createOrGetApplication
2018-05-11_13:25:42.11776     ser = plg.makeService(self.config.subOptions)
2018-05-11_13:25:42.11776   File "/opt/graphite/lib/twisted/plugins/carbon_cache_plugin.py", line 21, in makeService
2018-05-11_13:25:42.11776     return service.createCacheService(options)
2018-05-11_13:25:42.11776   File "/opt/graphite/lib/carbon/service.py", line 114, in createCacheService
2018-05-11_13:25:42.11776     setupPipeline(['write'], root_service, settings)
2018-05-11_13:25:42.11776   File "/opt/graphite/lib/carbon/service.py", line 89, in setupPipeline
2018-05-11_13:25:42.11777     setupWriterProcessor(root_service, settings)
2018-05-11_13:25:42.11777   File "/opt/graphite/lib/carbon/service.py", line 198, in setupWriterProcessor
2018-05-11_13:25:42.11777     from carbon.writer import WriterService
2018-05-11_13:25:42.11778   File "/opt/graphite/lib/carbon/writer.py", line 35, in <module>
2018-05-11_13:25:42.11778     SCHEMAS = loadStorageSchemas()
2018-05-11_13:25:42.11778   File "/opt/graphite/lib/carbon/storage.py", line 89, in loadStorageSchemas
2018-05-11_13:25:42.11779     archives = [Archive.fromString(s) for s in retentions]
2018-05-11_13:25:42.11779   File "/opt/graphite/lib/carbon/storage.py", line 74, in fromString
2018-05-11_13:25:42.11779     (secondsPerPoint, points) = parseRetentionDef(retentionDef)
2018-05-11_13:25:42.11779   File "/opt/graphite/lib/carbon/util.py", line 200, in parseRetentionDef
2018-05-11_13:25:42.11779     points = int(match.group(1)) * UnitMultipliers[getUnitString(match.group(2))] / precision
2018-05-11_13:25:42.11780   File "/opt/graphite/lib/carbon/util.py", line 176, in getUnitString
2018-05-11_13:25:42.11780     raise ValueError("Invalid unit '%s'" % s)
2018-05-11_13:25:42.11780 ValueError: Invalid unit 'min'

**Comment by deniszh** [comment]
You have error in schema file (storage-schemas.conf). Looks like you used 'min' as date suffix, which is not supported, please replace it with 'm' - please see documentation https://graphite.readthedocs.io/en/latest/config-carbon.html#storage-schemas-conf

**Comment by naveenlj** [comment]
Thank you, its working now.

**Comment by piotr1212** [comment]
https://github.com/graphite-project/carbon/pull/780 makes the error message a bit more human readable:

ex:
"Invalid unit 'day' in section [Default_1Min_For_1Day] in /home/piotr/git/carbon/conf/storage-schemas.conf"
