### ISSUE TITLE
'<' not supported between instances of 'tuple' and 'NoneType'

### ISSUE THREAD

**Issue by Quentin-M** [graphite-project/carbon#792]
Hi,

Our carbon-relays (1.1.3) are spamming the following stack traces, at an insane rate:

```
10/08/2018 01:13:18 :: [console] Unhandled Error
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/twisted/protocols/basic.py", line 766, in dataReceived
    self.stringReceived(packet)
  File "/opt/graphite/lib/carbon/protocols.py", line 242, in stringReceived
    self.metricReceived(metric, datapoint)
  File "/opt/graphite/lib/carbon/protocols.py", line 157, in metricReceived
    events.metricReceived(metric, datapoint)
  File "/opt/graphite/lib/carbon/events.py", line 17, in __call__
    handler(*args, **kwargs)
--- <exception caught here> ---
  File "/opt/graphite/lib/carbon/pipeline.py", line 31, in run_pipeline
    for out_metric, out_datapoint in processor.process(metric, datapoint):
  File "/opt/graphite/lib/carbon/client.py", line 569, in process
    state.client_manager.sendDatapoint(metric, datapoint)
  File "/opt/graphite/lib/carbon/client.py", line 554, in sendDatapoint
    for destination in self.getDestinations(metric):
  File "/opt/graphite/lib/carbon/client.py", line 546, in getDestinations
    destinations = list(self.router.getDestinations(metric))
  File "/opt/graphite/lib/carbon/routers.py", line 108, in getDestinations
    for (server, instance) in self.ring.get_nodes(key):
  File "/opt/graphite/lib/carbon/hashing.py", line 108, in get_nodes
    index = bisect.bisect_left(self.ring, search_entry) % self.ring_len
builtins.TypeError: '<' not supported between instances of 'tuple' and 'NoneType'
```

Our configuration looks like this:
```
[relay]
LINE_RECEIVER_INTERFACE = 0.0.0.0
LINE_RECEIVER_PORT = 2002

ENABLE_UDP_LISTENER = True
UDP_RECEIVER_INTERFACE = 0.0.0.0
UDP_RECEIVER_PORT = 2003

PICKLE_RECEIVER_INTERFACE = 0.0.0.0
PICKLE_RECEIVER_PORT = 2004

RELAY_METHOD = consistent-hashing
REPLICATION_FACTOR = 2
DIVERSE_REPLICAS = True
DESTINATIONS = graphite-cache-0.graphite-cache.app-devhk.svc.cluster.local:2004,graphite-cache-1.graphite-cache.app-devhk.svc.cluster.local:2004,graphite-cache-2.graphite-cache.app-devhk.svc.cluster.local:2004,graphite-cache-3.graphite-cache.app-devhk.svc.cluster.local:2004

MAX_QUEUE_SIZE = 10000
MAX_DATAPOINTS_PER_MESSAGE = 500
QUEUE_LOW_WATERMARK_PCT = 0.8
TIME_TO_DEFER_SENDING = 0.0001
USE_FLOW_CONTROL = True
USE_RATIO_RESET = False
MIN_RESET_STAT_FLOW = 1000
MIN_RESET_RATIO = 0.9
MIN_RESET_INTERVAL = 121
```

I have little clue on how to troubleshoot/fix this, unfortunately. Is there a way to early on print the message received to check if some of our applications are pushing bad metrics maybe? We do have a TCP socket healthcheck probe on port 2004 (pickle) that pings every few seconds, but the rate of the traces is waaayy higher.

Thanks!

**Comment by Quentin-M** [comment]
It would seem like running carbon from master fixed the issue, will update tomorrow once I have more data/confidence.

**Comment by piotr1212** [comment]
Yup that is fixed in master
