### ISSUE TITLE
Non english charactors throw error

### ISSUE THREAD

**Issue by yesoreyeram** [graphite-project/carbon#847]
Sometime my series have non english characters which resulting in followin error in carbon.  Example characters are `ÀÁÂÃÄÅàáâãäåÈÉÊËIлｔèｒｎåｔïｏｎɑｌíƶａｔï߀ԉ` .. How can i fix this error

12/03/2019 13:25:52 :: [console] Unhandled Error
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/twisted/protocols/basic.py", line 766, in dataReceived
    self.stringReceived(packet)
  File "/opt/graphite/lib/carbon/protocols.py", line 272, in stringReceived
    self.metricReceived(metric, datapoint)
  File "/opt/graphite/lib/carbon/protocols.py", line 182, in metricReceived
    events.metricReceived(metric, datapoint)
  File "/opt/graphite/lib/carbon/events.py", line 17, in __call__
    handler(*args, **kwargs)
--- <exception caught here> ---
  File "/opt/graphite/lib/carbon/pipeline.py", line 31, in run_pipeline
    for out_metric, out_datapoint in processor.process(metric, datapoint):
  File "/opt/graphite/lib/carbon/client.py", line 680, in process
    state.client_manager.sendDatapoint(metric, datapoint)
  File "/opt/graphite/lib/carbon/client.py", line 657, in sendDatapoint
    for factory in self.getFactories(metric):
  File "/opt/graphite/lib/carbon/client.py", line 635, in getFactories
    destinations = self.getDestinations(metric)
  File "/opt/graphite/lib/carbon/client.py", line 627, in getDestinations
    destinations = list(self.router.getDestinations(metric))
  File "/opt/graphite/lib/carbon/routers.py", line 108, in getDestinations
    for (server, instance) in self.ring.get_nodes(key):
  File "/opt/graphite/lib/carbon/hashing.py", line 106, in get_nodes
    position = self.compute_ring_position(key)
  File "/opt/graphite/lib/carbon/hashing.py", line 68, in compute_ring_position
    return carbonHash(key, self.hash_type)
  File "/opt/graphite/lib/carbon/hashing.py", line 51, in carbonHash
    big_hash = compactHash(key)
  File "/opt/graphite/lib/carbon/hashing.py", line 39, in compactHash
    return md5(string.encode('utf-8')).hexdigest()
exceptions.UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 39: ordinal not in range(128)

**Comment by piotr1212** [comment]
Assuming your clients are running Python 2. I think you are sending UTF-8 characters as 'str' object in pickle. You can fix this doing a .decode('UTF-8') on the metric name before sending, or send a 'unicode' object instead of 'str'.

Note that unicode metric names should work in carbon, but is not supported in graphite-web (there are known issues).
