### ISSUE TITLE
exceptions.TypeError: unsupported operand type(s) for +: 'float' and 'str'

### ISSUE THREAD

**Issue by seet61** [graphite-project/carbon#848]
I have a lot of errors in console,log:

`09/04/2019 11:44:36 :: Unhandled Error
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
    why = selectable.doRead()
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 1435, in doRead
    protocol.makeConnection(transport)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/protocol.py", line 514, in makeConnection
    self.connectionMade()
  File "/opt/graphite/lib/carbon/protocols.py", line 121, in connectionMade
    self.setTimeout(settings.METRIC_CLIENT_IDLE_TIMEOUT)
  File "/usr/local/lib/python2.7/dist-packages/twisted/protocols/policies.py", line 737, in setTimeout
    self.__timeoutCall = self.callLater(period, self.__timedOut)
  File "/usr/local/lib/python2.7/dist-packages/twisted/protocols/policies.py", line 697, in callLater
    return reactor.callLater(period, func)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 779, in callLater
    tple = DelayedCall(self.seconds() + _seconds, _f, args, kw,
exceptions.TypeError: unsupported operand type(s) for +: 'float' and 'str'
`

What does it meen?

**Comment by piotr1212** [comment]
Do you have an METRIC_CLIENT_IDLE_TIMEOUT configured in your carbon.conf?

**Comment by seet61** [comment]
# If enabled this setting is used to timeout metric client connection if no
# metrics have been sent in specified time in seconds
METRIC_CLIENT_IDLE_TIMEOUT = None

**Comment by deniszh** [comment]
@seet61 : could you please show all carbon.conf then, please?

**Comment by seet61** [comment]
But it is. I can't undestand too.

**Comment by piotr1212** [comment]
Looks like the config parameter is treated as string instead of NoneType or float. Try putting some number there. Otherwise some config processing must be added.

**Comment by seet61** [comment]
When I change METRIC_CLIENT_IDLE_TIMEOUT from None to 0, I lost other metrics.  I think it is incorrect.
![QIP Shot - Screen 002](https://user-images.githubusercontent.com/6140289/55854873-9b354300-5b6e-11e9-9a33-7f3f579be157.jpeg)

**Comment by piotr1212** [comment]
Not sure, but wouldn't none imply infinity?

**Comment by seet61** [comment]
May by I don't understand clearly. Could you please explain previous comment.

**Comment by piotr1212** [comment]
I think that if you set the timeout to None the timeout is infinite. Which means that it never times out. If you put it to 0, it times out immediately. So my suggestion would be to try some large value, like 300 for 5 minutes.

The exception looks like a bug which should be fixed, but I don't think that is what is causing your lost metrics. Why did you try to set the timeout in the first place, do you really need to set the timeout? If you are losing connections you might lower your os' tcp_keepalive_time.
