### ISSUE TITLE
[BUG] Manhole fails to find public cert

### ISSUE THREAD

**Issue by itinneed2022** [graphite-project/carbon#948]
**Please report bug only for carbon component here, if you want to to do so for Graphite, please use [graphite-web repo](https://github.com/graphite-project/graphite-web/issues/new/choose)**

**Describe the bug**
When trying to activate the manhole config, the certificate produced cannot be found at the location given.

**To Reproduce**
Produce ssh host key with:
`ckeygen -t rsa -f /app/graphite/conf/ssh_host_key_rsa`
Enable Manhole in carbon.conf:
```
ENABLE_MANHOLE = True
MANHOLE_INTERFACE = 127.0.0.1
MANHOLE_PORT = 7222
MANHOLE_USER = admin
MANHOLE_PUBLIC_KEY = ssh-rsa AAAAB3NzaC1yc2EAAAABiwAaAIEAoxN0sv/e4eZCPpi3N3KYvyzRaBaMeS2RsOQ/cDuKv11dlNzVeiyc3RFmCv5Rjwn/lQ79y0zyHxw67qLyhQ/kDzINc4cY41ivuQXm2tPmgvexdrBv5nsfEpjs3gLZfJnyvlcVyWK/lId8WUvEWSWHTzsbtmXAF2raJMdgLTbQ8wE=
MANHOLE_HOST_KEY_DIR = /app/graphite/conf/
```

Restart carbon-cache
`systemctl restart carbon-cache`

**Expected behavior**
An ssh port should be exposed that I can tunnel into the carbon-cache daemons and check their metrics.

**Environment (please complete the following information):**
 - OS flavor: Red Hat 7
 - Graphite version 1.1.0
 - Setup type: From Source
 - Python version: 3.6

**Additional context**
This is the error from the carbon-cache startup log:
```
16/08/2023 16:57:01 :: Traceback (most recent call last):
16/08/2023 16:57:01 ::   File "bin/carbon-cache.py", line 32, in <module>
16/08/2023 16:57:01 ::     run_twistd_plugin(__file__)
16/08/2023 16:57:01 ::   File "/app/graphite/lib/carbon/util.py", line 140, in run_twistd_plugin
16/08/2023 16:57:01 ::     runApp(config)
16/08/2023 16:57:01 ::   File "/usr/local/lib/python3.6/site-packages/twisted/scripts/twistd.py", line 29, in runApp
16/08/2023 16:57:01 ::     runner.run()
16/08/2023 16:57:01 ::   File "/usr/local/lib/python3.6/site-packages/twisted/application/app.py", line 374, in run
16/08/2023 16:57:01 ::     self.postApplication()
16/08/2023 16:57:01 ::   File "/usr/local/lib/python3.6/site-packages/twisted/scripts/_twistd_unix.py", line 254, in postApplication
16/08/2023 16:57:01 ::     self.startApplication(self.application)
16/08/2023 16:57:01 ::   File "/usr/local/lib/python3.6/site-packages/twisted/scripts/_twistd_unix.py", line 444, in startApplication
16/08/2023 16:57:01 ::     service.IService(application).privilegedStartService()
16/08/2023 16:57:01 ::   File "/usr/local/lib/python3.6/site-packages/twisted/application/service.py", line 271, in privilegedStartService
16/08/2023 16:57:01 ::     service.privilegedStartService()
16/08/2023 16:57:01 ::   File "/usr/local/lib/python3.6/site-packages/twisted/application/service.py", line 271, in privilegedStartService
16/08/2023 16:57:01 ::     service.privilegedStartService()
16/08/2023 16:57:01 ::   File "/usr/local/lib/python3.6/site-packages/twisted/application/internet.py", line 115, in privilegedStartService
16/08/2023 16:57:01 ::     self._port = self._getPort()
16/08/2023 16:57:01 ::   File "/usr/local/lib/python3.6/site-packages/twisted/application/internet.py", line 144, in _getPort
16/08/2023 16:57:01 ::     )(*self.args, **self.kwargs)
16/08/2023 16:57:01 ::   File "/usr/local/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 565, in listenTCP
16/08/2023 16:57:01 ::     p.startListening()
16/08/2023 16:57:01 ::   File "/usr/local/lib/python3.6/site-packages/twisted/internet/tcp.py", line 1356, in startListening
16/08/2023 16:57:01 ::     self.factory.doStart()
16/08/2023 16:57:01 ::   File "/usr/local/lib/python3.6/site-packages/twisted/internet/protocol.py", line 73, in doStart
16/08/2023 16:57:01 ::     self.startFactory()
16/08/2023 16:57:01 ::   File "/usr/local/lib/python3.6/site-packages/twisted/conch/ssh/factory.py", line 44, in startFactory
16/08/2023 16:57:01 ::     raise error.ConchError("no host public keys, failing")
16/08/2023 16:57:01 :: twisted.conch.error.ConchError: ('no host public keys, failing', None)

```

**Comment by deniszh** [comment]
Thanks for reporting. That's need to be checked and addressed, we'll do
that soon.

ср, 23 авг. 2023 г., 17:11 itinneed2022 ***@***.***>:

**Comment by deniszh** [comment]
@itinneed2022 : that's happening because of Twisted 16.1 and later is no longer uses a hardcoded SSH host key pair. 
So, for Twisted 16.1 and newer you need to set `MANHOLE_PUBLIC_KEY = None` and it works.
Probably easy fix in the code.

**Comment by deniszh** [comment]
Fixed for master in https://github.com/graphite-project/carbon/pull/950.
But `MANHOLE_PUBLIC_KEY = None` also works.

**Comment by deniszh** [comment]
What's in /app/graphite/example/host_keys directory?
You should have ssh_host_key_rsa and ssh_host_key_rsa.pub there, with proper permissions, available for read for carbon user.

**Comment by itinneed2022** [comment]
```
-rwxrwxrwx. 1 root root  886 Aug 16 15:12 ssh_host_key_rsa
-rwxrwxrwx. 1 root root  234 Aug 16 15:12 ssh_host_key_rsa.pub
```
