### ISSUE TITLE
REQ: Release for Python 3.12

### ISSUE THREAD

**Issue by twkiel** [graphite-project/carbon#954]
It appears Python 3.12 support was added in the last commit https://github.com/graphite-project/carbon/commit/66ebee19ece0e59d6a802d0ff77bead02191b7ab almost a year ago.

Could a release be created for this?

**Comment by deniszh** [comment]
Let me add Python 3.12 to tests first. Release should be done too, but we usually do that for a whole project, together with other components

**Comment by gramakri** [comment]
It seems out of the box carbon doesn't work on ubuntu 24.04 because of `imp`

```
root@f449ef810cb0:/app/code# /usr/bin/carbon-cache --debug --config=/etc/carbon/carbon.conf start
Traceback (most recent call last):
  File "/usr/bin/carbon-cache", line 32, in <module>
    run_twistd_plugin(__file__)
  File "/usr/lib/python3/dist-packages/carbon/util.py", line 71, in run_twistd_plugin
    from carbon.conf import get_parser
  File "/usr/lib/python3/dist-packages/carbon/conf.py", line 31, in <module>
    from carbon.routers import DatapointRouter
  File "/usr/lib/python3/dist-packages/carbon/routers.py", line 1, in <module>
    import imp
ModuleNotFoundError: No module named 'imp'
```

**Comment by randyrue** [comment]
Same problem. I either need to force python back or.... actually I don't see another option except carbon using the importlib module.

**Comment by gramakri** [comment]
It seems this project is a dead end and @deniszh spends time on the Go version. We switched to the Go version - https://github.com/go-graphite/go-carbon and that one works quite well!

**Comment by deniszh** [comment]
We need to migrate to importlib then, should work for all new python versions.
But go-carbon also an option ofc.
