### ISSUE TITLE
PLEASE HELP!!! Seeing some twisted-python error in my carbon-cache console.log file

### ISSUE THREAD

**Issue by rkr-23** [graphite-project/carbon#967]
Hello community. 

I'm seeing below errors in my console.log file. Its concerning that when this error occurs my carbon-cache will stop writing to the disk which causes my memory to be filled up and system invokes OOM. Please guide me how to fix this issue.

==> /var/log/carbon/console.log <==
21/11/2024 14:50:33 :: Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/usr/lib/python3/dist-packages/carbon/writer.py", line 189, in writeForever
    writeCachedDataPoints()
  File "/usr/lib/python3/dist-packages/carbon/writer.py", line 98, in writeCachedDataPoints
    (metric, datapoints) = cache.drain_metric()
  File "/usr/lib/python3/dist-packages/carbon/cache.py", line 187, in drain_metric
    metric = self.strategy.choose_item()
  File "/usr/lib/python3/dist-packages/carbon/cache.py", line 84, in choose_item
    metric_name, _ = max(self.cache.items(), key=lambda x: len(itemgetter(1)(x)))
builtins.RuntimeError: dictionary changed size during iteration

**Comment by deniszh** [comment]
What's your version? I believe fix was released with version 1.1.5 - https://github.com/graphite-project/carbon/issues/822

**Comment by rkr-23** [comment]
@deniszh 
I removed the apt package and now only have package from pip. `But` now I'm facing the below issue. Can you please help me. I'm new to these stuffs.

/usr/local/bin/carbon-cache.py
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (2.2.3) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Traceback (most recent call last):
  File "/usr/local/bin/carbon-cache.py", line 28, in <module>
    from carbon.util import run_twistd_plugin  # noqa
ModuleNotFoundError: No module named 'carbon'

**Comment by StudentCyberOps** [comment]
personally while installing carbon I get
Mar 24 10:30:01 jack-sparrow-ship systemd[1]: carbon-cache.service: Failed with result 'exit-code'.
Mar 24 10:30:01 jack-sparrow-ship systemd[1]: Failed to start carbon-cache.service - Graphite Carbon Cache.
