### ISSUE TITLE
Corrupt whispers files not handled properly

### ISSUE THREAD

**Issue by KlavsKlavsen** [graphite-project/carbon#99]
any ideas why I see these errors in console.log? or how I would go about debugging them?

```
17/04/2013 15:54:57 :: Error writing to /var/lib/carbon/whisper/servers/t-voduzi-pre/iostat/dm-0/reads_per_second.wsp
17/04/2013 15:54:57 :: Unhandled Error
Traceback (most recent call last):
  File "/usr/lib64/python2.6/site-packages/twisted/python/threadpool.py", line 210, in _worker
    result = context.call(ctx, function, *args, **kwargs)
  File "/usr/lib64/python2.6/site-packages/twisted/python/context.py", line 59, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib64/python2.6/site-packages/twisted/python/context.py", line 37, in callWithContext
    return func(*args,**kw)
  File "/usr/lib/python2.6/site-packages/carbon/writer.py", line 158, in writeForever
    writeCachedDataPoints()
--- <exception caught here> ---
  File "/usr/lib/python2.6/site-packages/carbon/writer.py", line 124, in writeCachedDataPoints
    whisper.update_many(dbFilePath, datapoints)
  File "/usr/lib/python2.6/site-packages/whisper.py", line 538, in update_many
    return file_update_many(fh, points)
  File "/usr/lib/python2.6/site-packages/whisper.py", line 572, in file_update_many
    __archive_update_many(fh,header,currentArchive,currentPoints)
  File "/usr/lib/python2.6/site-packages/whisper.py", line 640, in __archive_update_many
    if __propagate(fh, header, interval, higher, lower):
  File "/usr/lib/python2.6/site-packages/whisper.py", line 444, in __propagate
    (lowerBaseInterval,lowerBaseValue) = struct.unpack(pointFormat,packedPoint)
struct.error: unpack requires a string argument of length 12

17/04/2013 15:54:57 :: Sorted 41 cache queues in 0.000016 seconds
17/04/2013 15:54:57 :: Error writing to /var/lib/carbon/whisper/servers/t-voduzi-pre/sockets/tcp_alloc.wsp
17/04/2013 15:54:57 :: Unhandled Error
Traceback (most recent call last):
  File "/usr/lib64/python2.6/site-packages/twisted/python/threadpool.py", line 210, in _worker
    result = context.call(ctx, function, *args, **kwargs)
  File "/usr/lib64/python2.6/site-packages/twisted/python/context.py", line 59, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib64/python2.6/site-packages/twisted/python/context.py", line 37, in callWithContext
    return func(*args,**kw)
  File "/usr/lib/python2.6/site-packages/carbon/writer.py", line 158, in writeForever
    writeCachedDataPoints()
--- <exception caught here> ---
  File "/usr/lib/python2.6/site-packages/carbon/writer.py", line 124, in writeCachedDataPoints
    whisper.update_many(dbFilePath, datapoints)
  File "/usr/lib/python2.6/site-packages/whisper.py", line 538, in update_many
    return file_update_many(fh, points)
  File "/usr/lib/python2.6/site-packages/whisper.py", line 572, in file_update_many
    __archive_update_many(fh,header,currentArchive,currentPoints)
  File "/usr/lib/python2.6/site-packages/whisper.py", line 640, in __archive_update_many
    if __propagate(fh, header, interval, higher, lower):
  File "/usr/lib/python2.6/site-packages/whisper.py", line 444, in __propagate
    (lowerBaseInterval,lowerBaseValue) = struct.unpack(pointFormat,packedPoint)
struct.error: unpack requires a string argument of length 12
```

**Comment by filippog** [comment]
FWIW I've experienced sth similar with corrupted whisper files (`struct.error` actually) and at least on 0.9.13 this seems to crash/stop the thread writing to disk, therefore caching all metrics in memory if running with unlimited cache size

```
17/06/2015 00:56:12 :: [console] Error writing to PATH/data/WriteLatency/min.ws
p
17/06/2015 00:56:12 :: [console] Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 191, in _worker
    result = context.call(ctx, function, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
  File "/usr/lib/python2.7/dist-packages/carbon/writer.py", line 158, in writeForever
    writeCachedDataPoints()
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/carbon/writer.py", line 137, in writeCachedDataPoints
    whisper.update_many(dbFilePath, datapoints)
  File "/usr/lib/python2.7/dist-packages/whisper.py", line 577, in update_many
    return file_update_many(fh, points)
  File "/usr/lib/python2.7/dist-packages/whisper.py", line 611, in file_update_many
    __archive_update_many(fh,header,currentArchive,currentPoints)
  File "/usr/lib/python2.7/dist-packages/whisper.py", line 683, in __archive_update_many
    if __propagate(fh, header, interval, higher, lower):
  File "/usr/lib/python2.7/dist-packages/whisper.py", line 483, in __propagate
    (lowerBaseInterval,lowerBaseValue) = struct.unpack(pointFormat,packedPoint)
struct.error: unpack requires a string argument of length 12
```

**Comment by tbarbugli** [comment]
I ran into the same problem a few days after a big cleanup of whisper files (I simply rm'd some metrics I did not need anymore)

**Comment by avisri** [comment]
Ran into same issue while trying to do scaling . Simply removed the files which quick got recreated . 
grep 'Error writing to '   /opt/graphite/storage/log/carbon-cache/carbon-cache-a/console.log |awk '{print $NF}'  |sort -u | xargs  rm -f

**Comment by obfuscurity** [comment]
Curious what version of Graphite/Carbon folks are using that encounter this problem. IIRC this was related to corrupted Whisper files created during a full disk, and a fix finally went in to address this. I don't remember when this went in or which version but it would be nice to narrow it down.
